/**
 * Brand Kit PDF Export
 * Generates a branded PDF of the user's complete Brand Kit from Mission 2 (Story Builder).
 * Uses jsPDF for client-side generation — no server round-trip needed.
 */

// Dynamic import to keep bundle lean
export async function exportBrandKitPdf(data: {
  originStory: string;
  valueProposition: string;
  linkedinHeadline: string;
  pitch30: string;
  pitch60: string;
  linkedinAbout: string;
  userName?: string;
}) {
  const { jsPDF } = await import("jspdf");

  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  const W = 210;
  const MARGIN = 18;
  const CONTENT_W = W - MARGIN * 2;

  // ── Brand Colors ──────────────────────────────────────────────────────────────
  const NAVY = [15, 23, 42] as [number, number, number];
  const SKY = [59, 130, 246] as [number, number, number];
  const MINT = [16, 185, 129] as [number, number, number];
  const AMBER = [245, 158, 11] as [number, number, number];
  const IVORY = [250, 248, 245] as [number, number, number];
  const CHARCOAL = [51, 65, 85] as [number, number, number];
  const WHITE: [number, number, number] = [255, 255, 255];

  // ── Cover Page ────────────────────────────────────────────────────────────────
  // Navy background
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, W, 297, "F");

  // Sky blue accent bar at top
  doc.setFillColor(...SKY);
  doc.rect(0, 0, W, 4, "F");

  // Decorative circle (top right)
  doc.setFillColor(59, 130, 246, 0.08);
  doc.circle(W - 20, 40, 60, "F");

  // Logo area — LevelNext wordmark
  doc.setFontSize(11);
  doc.setTextColor(...SKY);
  doc.setFont("helvetica", "bold");
  doc.text("LEVELNEXT", MARGIN, 28);
  doc.setFontSize(7);
  doc.setTextColor(255, 255, 255, 0.4);
  doc.setFont("helvetica", "normal");
  doc.text("LAUNCH INTELLIGENCE", MARGIN, 33);

  // Main title
  doc.setFontSize(32);
  doc.setTextColor(...WHITE);
  doc.setFont("helvetica", "bold");
  doc.text("Your", MARGIN, 90);
  doc.setTextColor(...SKY);
  doc.text("Brand Kit", MARGIN, 105);

  doc.setFontSize(13);
  doc.setTextColor(255, 255, 255, 0.7);
  doc.setFont("helvetica", "normal");
  doc.text("Origin Story · Value Proposition · Elevator Pitches", MARGIN, 118);

  // User name
  if (data.userName) {
    doc.setFontSize(10);
    doc.setTextColor(255, 255, 255, 0.5);
    doc.text(`Prepared for ${data.userName}`, MARGIN, 132);
  }

  // Date
  const dateStr = new Date().toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });
  doc.setFontSize(9);
  doc.setTextColor(255, 255, 255, 0.35);
  doc.text(dateStr, MARGIN, 140);

  // 3 section badges at bottom of cover
  const badges = [
    { label: "Origin Story", color: MINT },
    { label: "Value Proposition", color: SKY },
    { label: "Elevator Pitches", color: AMBER },
  ];
  badges.forEach((b, i) => {
    const x = MARGIN + i * 60;
    doc.setFillColor(...b.color);
    doc.roundedRect(x, 240, 55, 8, 2, 2, "F");
    doc.setFontSize(7);
    doc.setTextColor(...WHITE);
    doc.setFont("helvetica", "bold");
    doc.text(b.label, x + 27.5, 245.2, { align: "center" });
  });

  // Footer
  doc.setFontSize(7);
  doc.setTextColor(255, 255, 255, 0.2);
  doc.setFont("helvetica", "normal");
  doc.text("Generated by LevelNext · levelnext.coach", W / 2, 285, { align: "center" });

  // ── Helper: add a content page ────────────────────────────────────────────────
  let currentY = 0;

  function addPage(sectionTitle: string, accentColor: [number, number, number]) {
    doc.addPage();
    // Ivory background
    doc.setFillColor(...IVORY);
    doc.rect(0, 0, W, 297, "F");

    // Top accent bar
    doc.setFillColor(...accentColor);
    doc.rect(0, 0, W, 3, "F");

    // Section label
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...accentColor);
    doc.text(sectionTitle.toUpperCase(), MARGIN, 18);

    // Divider
    doc.setDrawColor(...accentColor);
    doc.setLineWidth(0.4);
    doc.line(MARGIN, 21, W - MARGIN, 21);

    // Footer
    doc.setFontSize(7);
    doc.setTextColor(...CHARCOAL);
    doc.setFont("helvetica", "normal");
    doc.text("LevelNext Brand Kit · levelnext.coach", MARGIN, 290);
    doc.text(dateStr, W - MARGIN, 290, { align: "right" });

    currentY = 30;
  }

  function addHeading(text: string, color: [number, number, number] = NAVY) {
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...color);
    doc.text(text, MARGIN, currentY);
    currentY += 8;
  }

  function addSubheading(text: string) {
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...CHARCOAL);
    doc.text(text, MARGIN, currentY);
    currentY += 5;
  }

  function addBody(text: string, color: [number, number, number] = CHARCOAL) {
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...color);
    const lines = doc.splitTextToSize(text, CONTENT_W);
    doc.text(lines, MARGIN, currentY);
    currentY += lines.length * 5.5 + 4;
  }

  function addCard(content: string, bgColor: [number, number, number], textColor: [number, number, number] = WHITE) {
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    const lines = doc.splitTextToSize(content, CONTENT_W - 12);
    const cardH = lines.length * 5.5 + 10;
    doc.setFillColor(...bgColor);
    doc.roundedRect(MARGIN, currentY, CONTENT_W, cardH, 3, 3, "F");
    doc.setTextColor(...textColor);
    doc.text(lines, MARGIN + 6, currentY + 7);
    currentY += cardH + 6;
  }

  function addTip(text: string) {
    doc.setFontSize(8);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(100, 116, 139);
    const lines = doc.splitTextToSize(`💡 ${text}`, CONTENT_W);
    doc.text(lines, MARGIN, currentY);
    currentY += lines.length * 4.5 + 4;
  }

  // ── Page 2: Origin Story ──────────────────────────────────────────────────────
  addPage("Mission 2 · Story Builder", MINT);
  addHeading("Your Origin Story", NAVY);
  currentY += 2;
  addBody("This is your authentic professional narrative — where you came from, what drives you, and why you do what you do. Use it to open conversations, interviews, and networking moments.");
  currentY += 2;
  addCard(data.originStory, [16, 185, 129]);
  addTip("Use this as your opening when someone asks 'Tell me about yourself' at networking events or interviews.");

  // ── Page 3: Value Proposition ─────────────────────────────────────────────────
  addPage("Mission 2 · Story Builder", SKY);
  addHeading("Your Value Proposition", NAVY);
  currentY += 2;
  addBody("Your value proposition articulates what makes you uniquely valuable to employers and collaborators. It's the core of your professional brand.");
  currentY += 2;
  addCard(data.valueProposition, [59, 130, 246]);
  currentY += 4;

  addSubheading("LinkedIn Headline");
  currentY += 2;
  addCard(data.linkedinHeadline, [30, 64, 175], WHITE);
  addTip("Copy this headline directly to your LinkedIn profile. A strong headline gets 3× more profile views.");

  // ── Page 4: Elevator Pitches ──────────────────────────────────────────────────
  addPage("Mission 2 · Story Builder", AMBER);
  addHeading("Your Elevator Pitches", NAVY);
  currentY += 2;

  addSubheading("30-Second Pitch");
  addBody("Perfect for quick introductions, networking events, and the start of interviews.");
  addCard(data.pitch30, [245, 158, 11], NAVY);
  currentY += 4;

  addSubheading("60-Second Pitch");
  addBody("Use this when you have a bit more time — career fairs, informational interviews, or when someone asks 'So, what do you do?'");
  addCard(data.pitch60, [180, 120, 10], WHITE);

  // ── Page 5: LinkedIn About ────────────────────────────────────────────────────
  addPage("Mission 2 · Story Builder", [139, 92, 246]);
  addHeading("LinkedIn About Section", NAVY);
  currentY += 2;
  addBody("Your LinkedIn About section is your digital first impression. This AI-crafted version weaves together your story, value, and personality into a compelling narrative.");
  currentY += 2;
  addCard(data.linkedinAbout, [109, 40, 217], WHITE);
  addTip("Paste this directly into your LinkedIn profile's 'About' section. Add 2–3 relevant hashtags at the end.");

  // ── Page 6: Next Steps ────────────────────────────────────────────────────────
  addPage("Your Launch Journey", SKY);
  addHeading("What's Next?", NAVY);
  currentY += 4;

  const steps = [
    { num: "01", title: "Update LinkedIn", desc: "Copy your headline and About section to your LinkedIn profile today." },
    { num: "02", title: "Practice Your Pitch", desc: "Record yourself delivering your 30-second pitch. Aim for natural, not memorised." },
    { num: "03", title: "Share Your Story", desc: "Use your Origin Story in your next networking conversation or interview." },
    { num: "04", title: "Complete Mission 3", desc: "Head back to your Journey Map to unlock Skill Sprint and keep building momentum." },
  ];

  steps.forEach((s) => {
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(MARGIN, currentY, CONTENT_W, 18, 2, 2, "F");
    doc.setFillColor(...SKY);
    doc.roundedRect(MARGIN, currentY, 12, 18, 2, 2, "F");
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...WHITE);
    doc.text(s.num, MARGIN + 6, currentY + 11, { align: "center" });
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...NAVY);
    doc.text(s.title, MARGIN + 16, currentY + 7);
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...CHARCOAL);
    const descLines = doc.splitTextToSize(s.desc, CONTENT_W - 20);
    doc.text(descLines, MARGIN + 16, currentY + 13);
    currentY += 22;
  });

  // Save
  const fileName = `LevelNext_BrandKit_${data.userName?.replace(/\s+/g, "_") ?? "My"}.pdf`;
  doc.save(fileName);
}
