/**
 * ECI Profile PDF Export
 * Generates a branded PDF of the user's complete ECI profile including
 * archetype, development pathways, practice scenarios, and promotion readiness.
 * Uses jsPDF for client-side generation — no server round-trip needed.
 */

interface EciProfileData {
  archetype: {
    label: string;
    description: string;
    coreStrengths: string[];
    blindSpots: string[];
    developmentPriorities: string[];
  } | null;
  edgeScore: number | null;
  dimensionBands: { dimensionId: string; score: number; band: string }[];
  triggeredRisks: {
    id: string;
    label: string;
    behaviouralIndicators: string[];
    coachingPriorities: string[];
  }[];
  recommendedInterventions: {
    id: string;
    objective: string;
    practiceExercises: string[];
    aiSimulations: string[];
    successMetrics: string[];
    suggestedDurationWeeks: number;
  }[];
  recommendedScenarios: {
    id: string;
    dimensionId: string;
    difficulty: string;
    scenario: string;
  }[];
  promotionReadiness: {
    id: string;
    label: string;
    readinessAssessment: string;
    developmentFocus: string;
  }[];
  userName?: string;
}

export async function exportEciProfilePdf(data: EciProfileData) {
  const { jsPDF } = await import("jspdf");

  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  const W = 210;
  const MARGIN = 18;
  const CONTENT_W = W - MARGIN * 2;

  // ── Brand Colors ──────────────────────────────────────────────────────────────
  const NAVY: [number, number, number] = [15, 23, 42];
  const GOLD: [number, number, number] = [212, 175, 55];
  const IVORY: [number, number, number] = [250, 248, 245];
  const CHARCOAL: [number, number, number] = [51, 65, 85];
  const WHITE: [number, number, number] = [255, 255, 255];
  const RED: [number, number, number] = [220, 38, 38];
  const GREEN: [number, number, number] = [5, 150, 105];

  const dateStr = new Date().toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  // ── Cover Page ────────────────────────────────────────────────────────────────
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, W, 297, "F");

  // Gold accent bar at top
  doc.setFillColor(...GOLD);
  doc.rect(0, 0, W, 4, "F");

  // Decorative circle
  doc.setFillColor(212, 175, 55, 0.06);
  doc.circle(W - 20, 40, 60, "F");

  // Logo area
  doc.setFontSize(11);
  doc.setTextColor(...GOLD);
  doc.setFont("helvetica", "bold");
  doc.text("LEVELNEXT", MARGIN, 28);
  doc.setFontSize(7);
  doc.setTextColor(255, 255, 255, 0.4);
  doc.setFont("helvetica", "normal");
  doc.text("INTELLIGENCE CORE", MARGIN, 33);

  // Main title
  doc.setFontSize(32);
  doc.setTextColor(...WHITE);
  doc.setFont("helvetica", "bold");
  doc.text("Your", MARGIN, 90);
  doc.setTextColor(...GOLD);
  doc.text("ECI Profile", MARGIN, 105);

  doc.setFontSize(13);
  doc.setTextColor(255, 255, 255, 0.7);
  doc.setFont("helvetica", "normal");
  const subtitle = data.archetype
    ? `Archetype: ${data.archetype.label}`
    : "Executive Communication Intelligence";
  doc.text(subtitle, MARGIN, 118);

  // User name
  if (data.userName) {
    doc.setFontSize(10);
    doc.setTextColor(255, 255, 255, 0.5);
    doc.text(`Prepared for ${data.userName}`, MARGIN, 132);
  }

  // Date
  doc.setFontSize(9);
  doc.setTextColor(255, 255, 255, 0.35);
  doc.text(dateStr, MARGIN, 140);

  // Edge Score badge
  if (data.edgeScore !== null && data.edgeScore !== undefined) {
    doc.setFillColor(...GOLD);
    doc.roundedRect(MARGIN, 240, 80, 12, 2, 2, "F");
    doc.setFontSize(8);
    doc.setTextColor(...NAVY);
    doc.setFont("helvetica", "bold");
    doc.text(`EDGE Score: ${data.edgeScore}`, MARGIN + 40, 247, { align: "center" });
  }

  // Footer
  doc.setFontSize(7);
  doc.setTextColor(255, 255, 255, 0.2);
  doc.setFont("helvetica", "normal");
  doc.text("Generated by LevelNext Intelligence Core · levelnext.coach", W / 2, 285, { align: "center" });

  // ── Helper: add a content page ────────────────────────────────────────────────
  let currentY = 0;

  function addPage(sectionTitle: string, accentColor: [number, number, number]) {
    doc.addPage();
    doc.setFillColor(...IVORY);
    doc.rect(0, 0, W, 297, "F");

    // Top accent bar
    doc.setFillColor(...accentColor);
    doc.rect(0, 0, W, 3, "F");

    // Section label
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...accentColor);
    doc.text(sectionTitle.toUpperCase(), MARGIN, 18);

    // Divider
    doc.setDrawColor(...accentColor);
    doc.setLineWidth(0.4);
    doc.line(MARGIN, 21, W - MARGIN, 21);

    // Footer
    doc.setFontSize(7);
    doc.setTextColor(...CHARCOAL);
    doc.setFont("helvetica", "normal");
    doc.text("LevelNext ECI Profile · levelnext.coach", MARGIN, 290);
    doc.text(dateStr, W - MARGIN, 290, { align: "right" });

    currentY = 30;
  }

  function addHeading(text: string, color: [number, number, number] = NAVY) {
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...color);
    doc.text(text, MARGIN, currentY);
    currentY += 8;
  }

  function addSubheading(text: string) {
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...CHARCOAL);
    doc.text(text, MARGIN, currentY);
    currentY += 5;
  }

  function addBody(text: string, color: [number, number, number] = CHARCOAL) {
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...color);
    const lines = doc.splitTextToSize(text, CONTENT_W);
    doc.text(lines, MARGIN, currentY);
    currentY += lines.length * 5.5 + 4;
  }

  function addCard(content: string, bgColor: [number, number, number], textColor: [number, number, number] = WHITE) {
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    const lines = doc.splitTextToSize(content, CONTENT_W - 12);
    const cardH = lines.length * 5.5 + 10;
    doc.setFillColor(...bgColor);
    doc.roundedRect(MARGIN, currentY, CONTENT_W, cardH, 3, 3, "F");
    doc.setTextColor(...textColor);
    doc.text(lines, MARGIN + 6, currentY + 7);
    currentY += cardH + 6;
  }

  function addBulletList(items: string[], color: [number, number, number] = CHARCOAL) {
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...color);
    items.forEach(item => {
      const lines = doc.splitTextToSize(`• ${item}`, CONTENT_W - 6);
      doc.text(lines, MARGIN + 4, currentY);
      currentY += lines.length * 5 + 2;
    });
    currentY += 3;
  }

  function checkSpace(needed: number) {
    if (currentY + needed > 280) {
      doc.addPage();
      doc.setFillColor(...IVORY);
      doc.rect(0, 0, W, 297, "F");
      doc.setFontSize(7);
      doc.setTextColor(...CHARCOAL);
      doc.setFont("helvetica", "normal");
      doc.text("LevelNext ECI Profile · levelnext.coach", MARGIN, 290);
      doc.text(dateStr, W - MARGIN, 290, { align: "right" });
      currentY = 30;
    }
  }

  // ── Page 2: Archetype Overview ───────────────────────────────────────────────
  if (data.archetype) {
    addPage("Archetype Overview", GOLD);
    addHeading(data.archetype.label, NAVY);
    addBody(data.archetype.description);

    currentY += 2;
    addSubheading("Core Strengths");
    addBulletList(data.archetype.coreStrengths, GREEN);

    addSubheading("Blind Spots");
    addBulletList(data.archetype.blindSpots, RED);

    if (data.archetype.developmentPriorities.length > 0) {
      addSubheading("Development Priorities");
      addBulletList(data.archetype.developmentPriorities, GOLD);
    }
  }

  // ── Page 3: Dimension Scores ──────────────────────────────────────────────────
  if (data.dimensionBands.length > 0) {
    addPage("Dimension Scores", NAVY);
    addHeading("Your Communication Dimensions", NAVY);
    addBody("These are your scores across the 10 sub-dimensions of Executive Communication Intelligence, ranked from highest to lowest.");

    const sorted = [...data.dimensionBands].sort((a, b) => b.score - a.score);
    sorted.forEach(d => {
      checkSpace(12);
      // Bar background
      doc.setFillColor(230, 230, 235);
      doc.roundedRect(MARGIN, currentY, CONTENT_W, 8, 1.5, 1.5, "F");
      // Bar fill (proportional to score 0-100)
      const barW = (CONTENT_W * Math.min(d.score, 100)) / 100;
      const barColor: [number, number, number] = d.score >= 70 ? GREEN : d.score >= 50 ? GOLD : RED;
      doc.setFillColor(...barColor);
      doc.roundedRect(MARGIN, currentY, barW, 8, 1.5, 1.5, "F");
      // Label
      doc.setFontSize(8);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...NAVY);
      doc.text(d.dimensionId.replace(/_/g, " "), MARGIN + 3, currentY + 5.5);
      doc.text(`${d.score} (${d.band})`, W - MARGIN - 3, currentY + 5.5, { align: "right" });
      currentY += 11;
    });
  }

  // ── Page 4: Executive Risks ───────────────────────────────────────────────────
  if (data.triggeredRisks.length > 0) {
    addPage("Executive Risks", RED);
    addHeading("Risks to Watch", RED);
    addBody("Based on your assessment scores, these are the executive risks that require attention. Addressing them proactively will accelerate your development.");

    data.triggeredRisks.forEach(risk => {
      checkSpace(30);
      addSubheading(risk.label);
      addBody("Behavioural Indicators:", CHARCOAL);
      addBulletList(risk.behaviouralIndicators.slice(0, 3), RED);
      addBody("Coaching Priorities:", CHARCOAL);
      addBulletList(risk.coachingPriorities.slice(0, 3), NAVY);
    });
  }

  // ── Page 5: Development Pathways ──────────────────────────────────────────────
  if (data.recommendedInterventions.length > 0) {
    addPage("Development Pathways", GOLD);
    addHeading("Recommended Development Pathways", NAVY);
    addBody("These coaching interventions are tailored to your lowest-scoring dimensions. Each pathway includes practice exercises, AI simulations, and measurable success criteria.");

    data.recommendedInterventions.forEach((int, idx) => {
      checkSpace(40);
      currentY += 2;
      doc.setFillColor(248, 250, 252);
      doc.roundedRect(MARGIN, currentY, CONTENT_W, 14, 2, 2, "F");
      doc.setFillColor(...GOLD);
      doc.roundedRect(MARGIN, currentY, 12, 14, 2, 2, "F");
      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...NAVY);
      doc.text(String(idx + 1), MARGIN + 6, currentY + 9, { align: "center" });
      doc.setFontSize(10);
      doc.text(int.objective, MARGIN + 16, currentY + 6);
      doc.setFontSize(8);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...CHARCOAL);
      doc.text(`${int.suggestedDurationWeeks} weeks`, MARGIN + 16, currentY + 11);
      currentY += 18;

      addSubheading("Practice Exercises");
      addBulletList(int.practiceExercises.slice(0, 4), CHARCOAL);

      addSubheading("AI Simulations");
      addBulletList(int.aiSimulations.slice(0, 3), CHARCOAL);

      addSubheading("Success Metrics");
      addBulletList(int.successMetrics, GREEN);
    });
  }

  // ── Page 6: Practice Scenarios ───────────────────────────────────────────────
  if (data.recommendedScenarios.length > 0) {
    addPage("Practice Scenarios", NAVY);
    addHeading("Practice Scenarios", NAVY);
    addBody("These scenarios target your weakest dimensions. Practice them in real-world situations to build fluency and confidence.");

    data.recommendedScenarios.forEach((ps, idx) => {
      checkSpace(20);
      const diffColor: [number, number, number] =
        ps.difficulty === "Advanced" ? RED : ps.difficulty === "Intermediate" ? GOLD : GREEN;
      doc.setFillColor(248, 250, 252);
      doc.roundedRect(MARGIN, currentY, CONTENT_W, 16, 2, 2, "F");
      doc.setFillColor(...diffColor);
      doc.roundedRect(MARGIN, currentY, CONTENT_W, 3, 1.5, 1.5, "F");
      doc.setFontSize(7);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...diffColor);
      doc.text(ps.difficulty.toUpperCase(), MARGIN + 4, currentY + 8);
      doc.setFontSize(8);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...NAVY);
      doc.text(`[${ps.dimensionId.replace(/_/g, " ")}]`, MARGIN + 4, currentY + 12);
      const scenarioLines = doc.splitTextToSize(ps.scenario, CONTENT_W - 10);
      doc.setFontSize(9);
      doc.setTextColor(...CHARCOAL);
      doc.text(scenarioLines, MARGIN + 4, currentY + 16);
      currentY += 16 + scenarioLines.length * 5 + 4;
    });
  }

  // ── Page 7: Promotion Readiness ───────────────────────────────────────────────
  if (data.promotionReadiness.length > 0) {
    addPage("Promotion Readiness", GOLD);
    addHeading("Promotion Readiness Assessment", NAVY);
    addBody("This assessment evaluates your readiness for senior executive roles based on your ECI dimension scores.");

    data.promotionReadiness.forEach(pr => {
      checkSpace(25);
      addSubheading(pr.label);
      addBody(pr.readinessAssessment);
      doc.setFontSize(9);
      doc.setFont("helvetica", "italic");
      doc.setTextColor(...GOLD);
      const focusLines = doc.splitTextToSize(`Development Focus: ${pr.developmentFocus}`, CONTENT_W);
      doc.text(focusLines, MARGIN, currentY);
      currentY += focusLines.length * 5 + 6;
    });
  }

  // ── Final Page: Next Steps ────────────────────────────────────────────────────
  addPage("Your Next Steps", GOLD);
  addHeading("What's Next?", NAVY);
  currentY += 4;

  const steps = [
    { num: "01", title: "Review Your Archetype", desc: "Understand your communication archetype and how it shapes your executive presence." },
    { num: "02", title: "Practice Daily", desc: "Use the practice scenarios to build fluency in your weakest dimensions." },
    { num: "03", title: "Engage with Coaching", desc: "Work through the development pathways with your coach or independently." },
    { num: "04", title: "Track Your Progress", desc: "Use the Intelligence Core to track actions and outcomes over time." },
    { num: "05", title: "Re-assess", desc: "Re-take the ECI assessment after 6 months to measure your growth." },
  ];

  steps.forEach(s => {
    checkSpace(22);
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(MARGIN, currentY, CONTENT_W, 18, 2, 2, "F");
    doc.setFillColor(...GOLD);
    doc.roundedRect(MARGIN, currentY, 12, 18, 2, 2, "F");
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...NAVY);
    doc.text(s.num, MARGIN + 6, currentY + 11, { align: "center" });
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...NAVY);
    doc.text(s.title, MARGIN + 16, currentY + 7);
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...CHARCOAL);
    const descLines = doc.splitTextToSize(s.desc, CONTENT_W - 20);
    doc.text(descLines, MARGIN + 16, currentY + 13);
    currentY += 22;
  });

  // Save
  const fileName = `LevelNext_ECI_Profile_${data.userName?.replace(/\s+/g, "_") ?? "My"}.pdf`;
  doc.save(fileName);
}
