type PackData = {
  pilot: { name: string; organisation?: string | null; sponsorName?: string | null; businessProblem: string; whyItMatters?: string | null; targetBehaviours: string[]; day: number; accessLane: string; securityReviewStatus: string };
  metrics: { invited: number; baselineCompleted: number; firstReps: number; realWorkApplications: number; evidenceStrength: string; evidence: { system: number; behavioural: number; human: number; businessSignal: number }; health: { state: string; label: string; action: string } };
  headline: string;
  movement: string;
  proofPack: Array<{ label: string; value: string }>;
  scaleDecision: { strongestMovement: string; insufficientEvidence: string; securityNextStep: string };
  limitations: string[];
  momentsThatMattered: Array<{ type: string; source: string; evidenceLevel: number; summary: string }>;
  security: { requirements: Array<{ title: string; status: string; ownerName?: string | null; reviewNote?: string | null }>; documents: Array<{ title: string; status: string; reviewOwnerName?: string | null }> };
  communication: { privacy: { visibleToOrganisation: string[]; notVisibleToOrganisation: string[]; retention: string } };
};

const NAVY: [number, number, number] = [10, 26, 47];
const GOLD: [number, number, number] = [212, 175, 55];
const IVORY: [number, number, number] = [248, 245, 240];
const CHARCOAL: [number, number, number] = [28, 28, 28];
const W = 210; const H = 297; const M = 16; const CW = W - M * 2;

function cleanFileName(value: string) { return value.replace(/[^a-z0-9]+/gi, "_").replace(/^_+|_+$/g, "") || "Pilot_Proof"; }
async function loadLogo() {
  try { const response = await fetch("/logo.png"); if (!response.ok) return null; const blob = await response.blob(); return await new Promise<string | null>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(typeof reader.result === "string" ? reader.result : null); reader.onerror = reject; reader.readAsDataURL(blob); }); } catch { return null; }
}

function helpers(doc: any, logo: string | null, label: string) {
  const generated = new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });
  const text = (value: string, x: number, y: number, width: number, size = 9, color: [number, number, number] = CHARCOAL, style: "normal" | "bold" = "normal") => { doc.setFont("helvetica", style); doc.setFontSize(size); doc.setTextColor(...color); const lines = doc.splitTextToSize(value, width); doc.text(lines, x, y); return y + lines.length * size * 0.48; };
  const footer = () => { doc.setFont("helvetica", "normal"); doc.setFontSize(7); doc.setTextColor(100, 110, 120); doc.text(`LevelNext · ${label}`, M, 288); doc.text(generated, W - M, 288, { align: "right" }); };
  const page = (section: string) => { doc.addPage(); doc.setFillColor(...IVORY); doc.rect(0, 0, W, H, "F"); doc.setFillColor(...GOLD); doc.rect(0, 0, W, 3, "F"); if (logo) doc.addImage(logo, "PNG", M, 11, 29, 11); else { doc.setFont("helvetica", "bold"); doc.setFontSize(11); doc.setTextColor(...NAVY); doc.text("LEVELNEXT", M, 18); } doc.setFont("helvetica", "bold"); doc.setFontSize(8); doc.setTextColor(...GOLD); doc.text(section.toUpperCase(), W - M, 18, { align: "right" }); doc.setDrawColor(...GOLD); doc.line(M, 26, W - M, 26); footer(); };
  const cover = (title: string, subtitle: string, meta: string) => { doc.setFillColor(...NAVY); doc.rect(0, 0, W, H, "F"); doc.setFillColor(...GOLD); doc.rect(0, 0, W, 4, "F"); if (logo) doc.addImage(logo, "PNG", M, 20, 38, 15); else { doc.setFont("helvetica", "bold"); doc.setFontSize(13); doc.setTextColor(...GOLD); doc.text("LEVELNEXT", M, 30); } doc.setFont("helvetica", "bold"); doc.setFontSize(25); doc.setTextColor(...IVORY); doc.text(doc.splitTextToSize(title, 165), M, 94); doc.setFont("helvetica", "normal"); doc.setFontSize(12); doc.setTextColor(...GOLD); doc.text(subtitle, M, 127); doc.setFontSize(9); doc.setTextColor(215, 222, 231); doc.text(meta, M, 145); doc.setFontSize(8); doc.setTextColor(185, 194, 205); doc.text(`Generated ${generated}`, M, 270); doc.text("levelnext.coach", M, 282); };
  return { page, cover, text };
}

export async function exportPilotProofPackPdf(data: PackData) {
  const { jsPDF } = await import("jspdf"); const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" }); const logo = await loadLogo(); const { page, cover, text } = helpers(doc, logo, "Pilot Proof Pack");
  cover("30-Day Behaviour\nChange Proof", "Evidence-led pilot proof pack", `${data.pilot.name}${data.pilot.organisation ? ` · ${data.pilot.organisation}` : ""} · Day ${data.pilot.day} of 30`);
  page("Executive readout"); let y = 41; doc.setFont("helvetica", "bold"); doc.setFontSize(17); doc.setTextColor(...NAVY); doc.text(data.headline, M, y); y += 10; y = text(data.movement, M, y, CW, 10); y += 8;
  const stats = [["Participants", String(data.metrics.invited)], ["Baseline", `${data.metrics.baselineCompleted}/${data.metrics.invited}`], ["Behaviour Reps", String(data.metrics.firstReps)], ["Real-work actions", String(data.metrics.realWorkApplications)]];
  stats.forEach(([label, value], index) => { const x = M + (index % 2) * 90; const cy = y + Math.floor(index / 2) * 35; doc.setFillColor(255, 255, 255); doc.roundedRect(x, cy, 84, 28, 3, 3, "F"); doc.setFont("helvetica", "bold"); doc.setFontSize(7); doc.setTextColor(...NAVY); doc.text(label.toUpperCase(), x + 5, cy + 8); doc.setFontSize(17); doc.setTextColor(...GOLD); doc.text(value, x + 5, cy + 20); }); y += 82;
  doc.setFont("helvetica", "bold"); doc.setFontSize(12); doc.setTextColor(...NAVY); doc.text("Evidence and interpretation", M, y); y += 7; y = text(`Evidence strength: ${data.metrics.evidenceStrength.replace(/_/g, " ")}. The available signal mix is ${data.metrics.evidence.system} system, ${data.metrics.evidence.behavioural} behavioural, ${data.metrics.evidence.human} human, and ${data.metrics.evidence.businessSignal} business-signal observation(s). ${data.metrics.health.action}`, M, y, CW, 9); y += 8;
  doc.setFillColor(255, 248, 223); doc.roundedRect(M, y, CW, 42, 3, 3, "F"); doc.setFont("helvetica", "bold"); doc.setFontSize(9); doc.setTextColor(...NAVY); doc.text("Guarded scale decision", M + 6, y + 9); text(`Strongest movement: ${data.scaleDecision.strongestMovement}\nEvidence gap: ${data.scaleDecision.insufficientEvidence}\nSecurity next step: ${data.scaleDecision.securityNextStep}`, M + 6, y + 16, CW - 12, 8);
  page("Proof record"); y = 41; doc.setFont("helvetica", "bold"); doc.setFontSize(17); doc.setTextColor(...NAVY); doc.text("What the pilot is showing", M, y); y += 11;
  data.proofPack.forEach((item) => { doc.setFillColor(255, 255, 255); doc.roundedRect(M, y, CW, 26, 3, 3, "F"); doc.setFont("helvetica", "bold"); doc.setFontSize(7); doc.setTextColor(...GOLD); doc.text(item.label.toUpperCase(), M + 5, y + 7); text(item.value, M + 5, y + 14, CW - 10, 8.5); y += 31; });
  y += 3; doc.setFont("helvetica", "bold"); doc.setFontSize(12); doc.setTextColor(...NAVY); doc.text("Shareable moments", M, y); y += 8; const moments = data.momentsThatMattered.slice(0, 5); if (!moments.length) text("No sponsor-shareable moments have been recorded yet.", M, y, CW, 9); else moments.forEach((moment) => { doc.setFillColor(238, 244, 249); doc.roundedRect(M, y, CW, 22, 3, 3, "F"); doc.setFont("helvetica", "bold"); doc.setFontSize(7); doc.setTextColor(...GOLD); doc.text(`${moment.source.toUpperCase()} · ${moment.type.replace(/_/g, " ").toUpperCase()}`, M + 5, y + 7); text(moment.summary, M + 5, y + 13, CW - 10, 8); y += 27; });
  page("Governance and limitations"); y = 41; doc.setFont("helvetica", "bold"); doc.setFontSize(17); doc.setTextColor(...NAVY); doc.text("Use the proof responsibly", M, y); y += 10; y = text("This proof pack reports movement signals and pilot evidence. It does not establish causality, financial impact, a performance rating, or a basis for employment decisions.", M, y, CW, 10); y += 10;
  doc.setFont("helvetica", "bold"); doc.setFontSize(11); doc.setTextColor(...NAVY); doc.text("Participant privacy boundary", M, y); y += 7; y = text(`Organisation-visible: ${data.communication.privacy.visibleToOrganisation.join(" ")}\nNot organisation-visible: ${data.communication.privacy.notVisibleToOrganisation.join(" ")}\nRetention: ${data.communication.privacy.retention}`, M, y, CW, 8.5); y += 11;
  doc.setFont("helvetica", "bold"); doc.setFontSize(11); doc.setTextColor(...NAVY); doc.text("Security review status", M, y); y += 7; data.security.requirements.slice(0, 6).forEach((requirement) => { doc.setFillColor(255, 255, 255); doc.roundedRect(M, y, CW, 19, 3, 3, "F"); doc.setFont("helvetica", "bold"); doc.setFontSize(8); doc.setTextColor(...NAVY); doc.text(requirement.title, M + 5, y + 7); doc.setTextColor(...GOLD); doc.text(requirement.status.replace(/_/g, " ").toUpperCase(), W - M - 5, y + 7, { align: "right" }); if (requirement.ownerName) text(`Review owner: ${requirement.ownerName}`, M + 5, y + 14, CW - 10, 7.2); y += 23; }); y += 4; text(`Limitations: ${data.limitations.join(" ")}`, M, y, CW, 8.5);
  doc.save(`LevelNext_${cleanFileName(data.pilot.name)}_Pilot_Proof_Pack.pdf`);
}

export async function exportPilotBusinessCasePdf(data: PackData) {
  const { jsPDF } = await import("jspdf"); const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" }); const logo = await loadLogo(); const { page, cover, text } = helpers(doc, logo, "Internal Pilot Business Case");
  cover("Internal Business Case", "30-Day Behaviour Change Proof", `${data.pilot.name}${data.pilot.organisation ? ` · ${data.pilot.organisation}` : ""}`);
  page("Decision framing"); let y = 41; doc.setFont("helvetica", "bold"); doc.setFontSize(17); doc.setTextColor(...NAVY); doc.text("Why test this now", M, y); y += 10; y = text(data.pilot.whyItMatters || data.pilot.businessProblem, M, y, CW, 10); y += 12; doc.setFont("helvetica", "bold"); doc.setFontSize(11); doc.setTextColor(...NAVY); doc.text("Pilot hypothesis", M, y); y += 7; y = text(`If participants practise ${data.pilot.targetBehaviours.join(", ")} in situations already happening at work, the organisation can observe early movement signals before considering wider deployment. The pilot runs for 30 days with a small cohort and no required HRIS, CRM, calendar, collaboration-suite, or internal-document integration.`, M, y, CW, 9); y += 12; doc.setFont("helvetica", "bold"); doc.setFontSize(11); doc.setTextColor(...NAVY); doc.text("What the sponsor will decide", M, y); y += 7; text("Continue controlled testing, pause to address access or trust friction, or define an evidence-backed next cohort. This business case does not claim causal or financial impact from pilot evidence alone.", M, y, CW, 9);
  page("Operating model and controls"); y = 41; doc.setFont("helvetica", "bold"); doc.setFontSize(17); doc.setTextColor(...NAVY); doc.text("A bounded, governed pilot", M, y); y += 10; const controls = ["Sponsor-led invitation with plain-language selection rationale and privacy explanation", "Participant personal goal, real-work practice, daily micro-actions, and optional fewer nudges", `Access lane: ${data.pilot.accessLane.replace(/_/g, " ")}`, "Private coaching and reflection text excluded from sponsor reporting", "Security workspace with review owners, evidence documents, and requirement-level approval tracking", "Day-3, Day-7, Day-15, and Day-30 sponsor and participant milestone nudges"];
  controls.forEach((control, index) => { doc.setFillColor(255, 255, 255); doc.roundedRect(M, y, CW, 19, 3, 3, "F"); doc.setFillColor(...GOLD); doc.circle(M + 7, y + 9.5, 3, "F"); doc.setFont("helvetica", "bold"); doc.setFontSize(7); doc.setTextColor(...NAVY); doc.text(String(index + 1), M + 7, y + 10.5, { align: "center" }); text(control, M + 15, y + 11, CW - 21, 8.2); y += 24; });
  page("Evidence plan and recommendation"); y = 41; doc.setFont("helvetica", "bold"); doc.setFontSize(17); doc.setTextColor(...NAVY); doc.text("What will make a next decision credible", M, y); y += 10; y = text(`Current evidence strength: ${data.metrics.evidenceStrength.replace(/_/g, " ")}. The next decision should consider activation, Behaviour Reps, real-work applications, appropriate human observation, access friction, and unresolved security requirements—not activity volume alone.`, M, y, CW, 9.5); y += 11;
  doc.setFillColor(255, 248, 223); doc.roundedRect(M, y, CW, 52, 3, 3, "F"); doc.setFont("helvetica", "bold"); doc.setFontSize(10); doc.setTextColor(...NAVY); doc.text("Recommended decision posture", M + 6, y + 10); text(`Continue controlled testing. ${data.scaleDecision.insufficientEvidence} ${data.scaleDecision.securityNextStep}`, M + 6, y + 18, CW - 12, 9); y += 63;
  doc.setFont("helvetica", "bold"); doc.setFontSize(11); doc.setTextColor(...NAVY); doc.text("Required readiness before broader deployment", M, y); y += 7; data.security.requirements.filter((item) => item.status !== "approved" && item.status !== "not_applicable").slice(0, 5).forEach((item) => { y = text(`• ${item.title}: ${item.status.replace(/_/g, " ")}${item.ownerName ? ` · owner ${item.ownerName}` : ""}`, M, y, CW, 8.5); y += 3; });
  doc.save(`LevelNext_${cleanFileName(data.pilot.name)}_Internal_Business_Case.pdf`);
}
