CREATE TABLE `access_paths` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`opportunityId` int NOT NULL,
	`companyName` varchar(200) NOT NULL,
	`targetRole` varchar(200),
	`decisionMakers` json DEFAULT ('[]'),
	`bestPath` json,
	`alternativePath` json,
	`fastestPath` json,
	`safestPath` json,
	`highestProbabilityPath` json,
	`mutualConnections` json DEFAULT ('[]'),
	`warmIntroRequest` text,
	`directOutreachEmail` text,
	`linkedinMessage` text,
	`overallAccessScore` int,
	`primaryBarrier` text,
	`keyInsight` text,
	`status` varchar(30) NOT NULL DEFAULT 'not_started',
	`userNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `access_paths_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `relationship_contacts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(200) NOT NULL,
	`currentTitle` varchar(200),
	`currentCompany` varchar(200),
	`industry` varchar(100),
	`geography` varchar(100),
	`linkedinUrl` varchar(500),
	`email` varchar(200),
	`phone` varchar(50),
	`relationshipType` varchar(50) NOT NULL,
	`howWeKnowEachOther` text,
	`sharedHistory` text,
	`scoreTrust` int,
	`scoreInfluence` int,
	`scoreAccessibility` int,
	`scoreRecency` int,
	`scoreWarmth` int,
	`scoreStrategicValue` int,
	`scoreLikelihoodToHelp` int,
	`compositeScore` int,
	`recommendedAction` varchar(50),
	`recommendedActionReason` text,
	`nextActionDue` timestamp,
	`lastContactDate` timestamp,
	`contactFrequencyDays` int DEFAULT 90,
	`notes` text,
	`linkedOpportunityIds` json DEFAULT ('[]'),
	`isKeyConnector` boolean DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `relationship_contacts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
ALTER TABLE `access_paths` ADD CONSTRAINT `access_paths_userId_users_id_fk` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `access_paths` ADD CONSTRAINT `access_paths_opportunityId_opportunity_universe_id_fk` FOREIGN KEY (`opportunityId`) REFERENCES `opportunity_universe`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `relationship_contacts` ADD CONSTRAINT `relationship_contacts_userId_users_id_fk` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action;