import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, BrainCircuit, CheckCircle2, Compass, Download, Lightbulb, Loader2, ShieldCheck, Target } from "lucide-react";
import { Radar, RadarChart, PolarGrid, PolarAngleAxis, ResponsiveContainer, Tooltip } from "recharts";
import { useLocation, useRoute } from "wouter";

export default function CriticalThinkingReport() {
  const [, params] = useRoute("/critical-thinking/report/:reportId");
  const reportId = Number(params?.reportId);
  const [, setLocation] = useLocation();
  const { data, isLoading, error } = trpc.criticalThinking.getMyReport.useQuery({ reportId }, { enabled: Number.isFinite(reportId) && reportId > 0 });
  if (isLoading) return <div className="grid min-h-screen place-items-center bg-[var(--color-ln-ivory)]"><Loader2 className="h-6 w-6 animate-spin text-[#12345A]" /></div>;
  if (!data || error) return <div className="grid min-h-screen place-items-center bg-[var(--color-ln-ivory)] p-6"><Card className="max-w-lg"><CardHeader><CardTitle>Report unavailable</CardTitle><CardDescription>{error?.message ?? "This private developmental report could not be found."}</CardDescription></CardHeader><CardContent><Button onClick={() => setLocation("/critical-thinking")}>Return to diagnostic home</Button></CardContent></Card></div>;
  const score = data.report.scoreSnapshot as any;
  const dimensions = data.dimensions;
  const radarData = dimensions.map((dimension: any) => ({ dimension: dimension.label, score: score.dimensionScores?.[dimension.id] ?? 0 }));
  const getDimension = (id: string) => dimensions.find((dimension: any) => dimension.id === id);
  const strengths = (score.strengths ?? []).map(getDimension).filter(Boolean);
  const priorities = (score.priorities ?? []).map(getDimension).filter(Boolean);
  const startDate = new Date(data.report.createdAt);
  return <main className="min-h-screen bg-[var(--color-ln-ivory)] pb-12"><header className="border-b bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4 sm:px-8"><img src="/logo.png" alt="LevelNext" className="h-8 w-auto" /><Button variant="outline" onClick={() => window.print()}><Download className="mr-2 h-4 w-4" />Save as PDF</Button></div></header><div className="mx-auto max-w-6xl px-5 py-8 sm:px-8"><Button variant="ghost" className="mb-6 -ml-3" onClick={() => setLocation("/critical-thinking")}><ArrowLeft className="mr-2 h-4 w-4" />Back to diagnostic home</Button><section className="overflow-hidden rounded-2xl bg-[#0A1A2F] p-7 text-white shadow-xl sm:p-10"><div className="grid gap-7 lg:grid-cols-[1.3fr_.7fr]"><div><Badge className="mb-4 bg-[#F2B705] text-[#12345A] hover:bg-[#F2B705]">Private developmental report</Badge><h1 className="text-3xl font-bold sm:text-4xl">Critical Thinking in Decision Making</h1><p className="mt-4 max-w-2xl leading-7 text-slate-200">A practical snapshot of your reported decision practices, applied judgment in eight workplace scenarios, confidence calibration, and the conditions around you.</p><p className="mt-6 text-sm text-slate-300">Completed {startDate.toLocaleDateString(undefined, { year: "numeric", month: "long", day: "numeric" })}</p></div><div className="rounded-xl border border-white/10 bg-white/8 p-5"><p className="text-xs font-semibold uppercase tracking-widest text-slate-300">A developmental reminder</p><p className="mt-3 text-sm leading-6 text-slate-100">This report is not a performance rating, intelligence test, or employment decision tool. Use it to select one or two practices to test in live decisions.</p></div></div></section>
  <section className="mt-8 grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><Card><CardHeader><div className="flex items-center gap-2"><BrainCircuit className="h-5 w-5 text-[#12345A]" /><CardTitle>Your seven-capability profile</CardTitle></div><CardDescription>Dimension results are reported separately rather than combined into a single critical-thinking label.</CardDescription></CardHeader><CardContent><div className="h-80"><ResponsiveContainer width="100%" height="100%"><RadarChart data={radarData}><PolarGrid stroke="#d6deea" /><PolarAngleAxis dataKey="dimension" tick={{ fontSize: 11, fill: "#12345A" }} /><Radar name="Current profile" dataKey="score" stroke="#12345A" fill="#F2B705" fillOpacity={0.45} /><Tooltip /></RadarChart></ResponsiveContainer></div></CardContent></Card><Card><CardHeader><CardTitle>Two results that should stay distinct</CardTitle><CardDescription>Scenario judgment checks applied choice under ambiguity. Confidence calibration describes the relationship between confidence and this brief scenario sample.</CardDescription></CardHeader><CardContent className="space-y-4"><Metric label="Applied judgment" value={score.appliedJudgmentScore} detail={`${score.scenarioCount ?? 0} of 8 scenarios completed`} /><Metric label="Average confidence" value={score.meanConfidence} detail={score.calibration?.label ?? "Complete scenarios to view"} /><Metric label="Bias-management practices" value={score.biasManagementScore} detail="Observable countermeasures, not bias terminology" /><Metric label="Intellectual habits" value={score.intellectualHabitsScore} detail="A learnable developmental signal, not a personality score" /></CardContent></Card></section>
  <section className="mt-6 grid gap-6 md:grid-cols-2"><Card className="border-emerald-100"><CardHeader><div className="flex items-center gap-2"><CheckCircle2 className="h-5 w-5 text-emerald-600" /><CardTitle>Demonstrated strengths</CardTitle></div><CardDescription>Relative strengths in this current response set.</CardDescription></CardHeader><CardContent className="space-y-4">{strengths.map((dimension: any) => <FeedbackCard key={dimension.id} title={dimension.label} text={dimension.feedback.strong} />)}</CardContent></Card><Card className="border-[#F2B705]/50"><CardHeader><div className="flex items-center gap-2"><Target className="h-5 w-5 text-[#12345A]" /><CardTitle>Development priorities</CardTitle></div><CardDescription>Choose one behaviour to practise before trying to improve every score.</CardDescription></CardHeader><CardContent className="space-y-4">{priorities.map((dimension: any) => <FeedbackCard key={dimension.id} title={dimension.label} text={dimension.feedback.priority} />)}</CardContent></Card></section>
  <section className="mt-6 grid gap-6 lg:grid-cols-2"><Card><CardHeader><div className="flex items-center gap-2"><Compass className="h-5 w-5 text-[#12345A]" /><CardTitle>Decision environment</CardTitle></div><CardDescription>Your environment is reported separately and does not reduce your individual capability profile.</CardDescription></CardHeader><CardContent><Metric label={score.environmentBand ?? "Environment signal"} value={score.environmentScore} detail={score.environmentBand === "Constraining" ? "The context may make evidence, dissent, or review difficult; focus on small practices within your influence." : score.environmentBand === "Enabling" ? "The reported context contains useful conditions for disciplined decision making. Use them deliberately." : "Conditions appear uneven. Identify which routines or leaders would make decision quality more consistent."} /></CardContent></Card><Card><CardHeader><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-[#12345A]" /><CardTitle>Interpret with care</CardTitle></div><CardDescription>{score.interpretation}</CardDescription></CardHeader><CardContent className="text-sm leading-6 text-slate-600"><p>This comparison does not diagnose honesty or competence. Different patterns can reflect decision context, experience, confidence, interpretation of the items, or the limits of eight scenarios.</p><p className="mt-4">{score.calibration?.description}</p></CardContent></Card></section>
  <section className="mt-6"><Card><CardHeader><div className="flex items-center gap-2"><Lightbulb className="h-5 w-5 text-[#F2B705]" /><CardTitle>30-day development plan</CardTitle></div><CardDescription>Work with one priority in a live decision; aim for repetition and review rather than perfect analysis.</CardDescription></CardHeader><CardContent className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{priorities.slice(0, 2).flatMap((dimension: any) => [1, 2]).map((week: number, index: number) => { const dimension = priorities[Math.floor(index / 2)] as any; return <div key={`${dimension.id}-${week}`} className="rounded-xl border bg-white p-4"><p className="text-xs font-semibold uppercase tracking-widest text-[#12345A]">Week {index + 1}</p><h3 className="mt-2 font-semibold">{dimension.label}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{index % 2 === 0 ? dimension.individualPractice : dimension.reflectionQuestion}</p><p className="mt-3 text-xs font-medium text-[#12345A]">Tool: {dimension.reusableTool}</p></div> })}</CardContent></Card></section></div></main>;
}
function Metric({ label, value, detail }: { label: string; value: number | null | undefined; detail: string }) { return <div className="rounded-xl border border-slate-100 bg-slate-50 p-4"><div className="flex items-end justify-between gap-3"><p className="font-semibold text-[#12345A]">{label}</p>{typeof value === "number" && <p className="text-2xl font-bold">{value}<span className="text-sm text-slate-500">/100</span></p>}</div><p className="mt-2 text-sm leading-5 text-slate-600">{detail}</p></div>; }
function FeedbackCard({ title, text }: { title: string; text: string }) { return <div className="rounded-xl bg-slate-50 p-4"><h3 className="font-semibold text-[#12345A]">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></div>; }
