import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { Building2, CheckCircle2, Loader2, PauseCircle, PlayCircle, ShieldCheck } from "lucide-react";

export default function CriticalThinkingPlatformAdmin() {
  const { data, isLoading, error, refetch } = trpc.criticalThinking.platformCampaigns.useQuery();
  const status = trpc.criticalThinking.platformSetCampaignStatus.useMutation({ onSuccess: () => refetch() });
  if (isLoading) return <DashboardLayout><div className="grid min-h-96 place-items-center"><Loader2 className="h-6 w-6 animate-spin text-[#12345A]" /></div></DashboardLayout>;
  if (error || !data) return <DashboardLayout><Card className="max-w-2xl"><CardHeader><CardTitle>Platform administrator access is required</CardTitle><CardDescription>{error?.message ?? "This cross-tenant view is available only to LevelNext platform administrators."}</CardDescription></CardHeader></Card></DashboardLayout>;
  const active = data.filter((entry) => entry.campaign.status === "active").length;
  const completed = data.reduce((sum, entry) => sum + entry.completedCount, 0);
  return <DashboardLayout><div className="mx-auto max-w-7xl space-y-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><Badge className="mb-3 bg-[#12345A]">Platform administrator</Badge><h1 className="text-3xl font-bold">Critical Thinking oversight</h1><p className="mt-2 max-w-3xl text-slate-600">Cross-tenant campaign health, completion visibility, and status control. Individual response content and individual developmental reports remain outside this platform view.</p></div><ShieldCheck className="h-11 w-11 text-[#F2B705]" /></div><div className="grid gap-4 sm:grid-cols-3"><Metric label="Tenant campaigns" value={data.length} icon={<Building2 className="h-5 w-5" />} /><Metric label="Active campaigns" value={active} icon={<PlayCircle className="h-5 w-5" />} /><Metric label="Completed diagnostics" value={completed} icon={<CheckCircle2 className="h-5 w-5" />} /></div><Card><CardHeader><CardTitle>Campaign portfolio</CardTitle><CardDescription>Status controls are logged to the tenant-specific administrative audit. Closing a campaign prevents new participant starts while retaining existing developmental records according to its retention policy.</CardDescription></CardHeader><CardContent><div className="overflow-auto rounded-xl border"><table className="w-full min-w-190 text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="p-4">Tenant</th><th className="p-4">Campaign</th><th className="p-4">Group</th><th className="p-4">Completion</th><th className="p-4">Status</th><th className="p-4">Control</th></tr></thead><tbody>{data.map(({ campaign, tenant, participantCount, completedCount }) => <tr key={campaign.id} className="border-t"><td className="p-4"><p className="font-medium">{tenant.name}</p><p className="mt-1 text-xs text-slate-500">{tenant.slug}</p></td><td className="p-4 font-medium">{campaign.name}</td><td className="p-4 text-slate-600">{campaign.reportingGroup}</td><td className="p-4">{completedCount} / {participantCount}</td><td className="p-4"><Badge variant="outline">{campaign.status}</Badge></td><td className="p-4">{campaign.status === "active" ? <Button size="sm" variant="outline" disabled={status.isPending} onClick={() => status.mutate({ campaignId: campaign.id, status: "closed" })}><PauseCircle className="mr-2 h-4 w-4" />Close</Button> : <Button size="sm" disabled={status.isPending} onClick={() => status.mutate({ campaignId: campaign.id, status: "active" })}><PlayCircle className="mr-2 h-4 w-4" />Activate</Button>}</td></tr>)}</tbody></table></div>{!data.length && <p className="py-8 text-center text-sm text-slate-600">No tenant campaigns have been created yet.</p>}</CardContent></Card></div></DashboardLayout>;
}
function Metric({ label, value, icon }: { label: string; value: number; icon: React.ReactNode }) { return <Card><CardContent className="flex items-center gap-4 p-5"><div className="rounded-lg bg-[#12345A]/5 p-3 text-[#12345A]">{icon}</div><div><p className="text-sm text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></div></CardContent></Card>; }
