import { IndividualReportPreview, TeamReportPreview } from "@/components/CriticalThinkingReportPreview";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { compareCriticalThinkingCycles } from "@shared/modules/criticalThinkingComparison";
import { useState } from "react";

const dimensions = ["frame", "question", "evidence", "options", "challenge", "decide", "learn"].map((id) => ({ id, label: id.replace(/^./, (letter) => letter.toUpperCase()) }));
const baseline = { dimensionScores: { frame: 61, question: 69, evidence: 66, options: 63, challenge: 59, decide: 68, learn: 62 }, appliedJudgmentScore: 64, meanConfidence: 68, biasManagementScore: 61, intellectualHabitsScore: 64, environmentScore: 57 };
const current = { dimensionScores: { frame: 74, question: 71, evidence: 70, options: 69, challenge: 66, decide: 73, learn: 70 }, appliedJudgmentScore: 76, meanConfidence: 71, biasManagementScore: 70, intellectualHabitsScore: 72, environmentScore: 61, strengths: ["frame", "decide"], priorities: ["challenge", "options"], environmentBand: "Mixed", calibration: { label: "Balanced" } };
const aggregate = { participantCount: 5, averageAppliedJudgmentScore: 72, averageBehaviouralScore: 70, averageEnvironmentScore: 63, dimensionAverages: current.dimensionScores, sharedStrengths: ["frame"], sharedPriorities: ["challenge"] };

export default function CriticalThinkingReportValidationFixture() {
  const requestedModal = window.location.pathname.endsWith("/individual") ? "individual" : window.location.pathname.endsWith("/team") ? "team" : null;
  const [individualOpen, setIndividualOpen] = useState(requestedModal === "individual"); const [teamOpen, setTeamOpen] = useState(requestedModal === "team"); const comparison = compareCriticalThinkingCycles(baseline, current);
  return <main className="min-h-screen bg-[var(--color-ln-ivory)] px-5 py-10 text-[var(--color-ln-text)]"><div className="mx-auto max-w-5xl"><p className="text-xs font-semibold uppercase tracking-widest text-[#12345A]">Development-only validation fixture</p><h1 className="mt-2 text-3xl font-bold">Report preview and progress comparison</h1><p className="mt-2 max-w-3xl text-slate-600">Synthetic, non-persistent values are used only to verify responsive composition. This route is excluded from production.</p><Card className="mt-6"><CardHeader><CardTitle>Progress across diagnostic cycles</CardTitle><CardDescription>Baseline leadership cycle → Current leadership cycle</CardDescription></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{comparison.dimensions.map((dimension) => <div key={dimension.id} className="rounded-xl border bg-white p-4"><p className="font-semibold text-[#12345A]">{dimension.label}</p><p className="mt-2 text-sm text-slate-600">{dimension.baseline} → <strong className="text-slate-900">{dimension.current}</strong></p><p className="mt-1 font-bold text-emerald-700">{dimension.delta && dimension.delta > 0 ? "+" : ""}{dimension.delta}</p></div>)}</CardContent></Card><div className="mt-6 flex flex-wrap gap-3"><Button onClick={() => setIndividualOpen(true)}>Preview individual report</Button><Button variant="outline" onClick={() => setTeamOpen(true)}>Preview team report</Button></div></div><IndividualReportPreview open={individualOpen} onOpenChange={setIndividualOpen} campaignName="Current leadership cycle" completedAt={new Date("2026-08-20")} score={current} dimensions={dimensions} onDownload={() => setIndividualOpen(false)} exporting={false} /><TeamReportPreview open={teamOpen} onOpenChange={setTeamOpen} campaignName="Current leadership cycle" reportingGroup="Pilot cohort" participantCount={5} minTeamSize={5} aggregate={aggregate} dimensions={dimensions} onDownload={() => setTeamOpen(false)} exporting={false} /></main>;
}
