import { useMemo, useState } from "react";
import { ArrowRight, Check, CircleAlert, LockKeyhole, MessageSquare, ShieldCheck, Sparkles } from "lucide-react";
import { useRoute } from "wouter";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";

export default function PilotParticipant() {
  const [, params] = useRoute("/pilot/participant/:token");
  const token = params?.token ?? "";
  const participant = trpc.behaviourChangeProof.participant.useQuery({ token }, { enabled: Boolean(token) });
  const [situation, setSituation] = useState("");
  const [desiredMovement, setDesiredMovement] = useState("");
  const [practiceRole, setPracticeRole] = useState("");
  const [situationType, setSituationType] = useState("");
  const [actionTaken, setActionTaken] = useState("");
  const [outcomeSignal, setOutcomeSignal] = useState("");
  const [movement, setMovement] = useState<"not_yet" | "early_signal" | "consistent_signal">("early_signal");
  const [notice, setNotice] = useState("");
  const baseline = trpc.behaviourChangeProof.completeBaseline.useMutation({ onSuccess: () => { setNotice("Baseline saved. Now try a short Behaviour Rep."); void participant.refetch(); } });
  const rep = trpc.behaviourChangeProof.completeRep.useMutation({ onSuccess: () => { setNotice("Rep completed. Bring the behaviour into a real moment at work."); void participant.refetch(); } });
  const realWork = trpc.behaviourChangeProof.recordRealWork.useMutation({ onSuccess: () => { setNotice("Real-work application recorded. That is the evidence loop in action."); void participant.refetch(); } });
  const pulse = trpc.behaviourChangeProof.observerPulse.useMutation({ onSuccess: () => { setNotice("Pulse recorded. Thank you for helping the sponsor see movement without exposing private reflection."); void participant.refetch(); } });
  const stage = useMemo(() => { const current = participant.data?.participant; if (!current) return 1; if (!current.baselineCompleted) return 1; if (!current.firstRepCompleted) return 2; if (!current.firstRealWorkApplication) return 3; return 4; }, [participant.data]);

  if (participant.isLoading) return <div className="grid min-h-screen place-items-center bg-[#F8F5F0] text-[#0A1A2F]">Preparing your 30-day proof…</div>;
  if (participant.error || !participant.data) return <main className="grid min-h-screen place-items-center bg-[#F8F5F0] px-6"><Card className="max-w-md border-[#DCE3EA] bg-white"><CardContent className="space-y-4 p-8 text-center"><CircleAlert className="mx-auto text-red-500" size={30} /><h1 className="text-2xl font-bold text-[#0A1A2F]">This invite is unavailable.</h1><p className="text-sm leading-6 text-slate-600">It may have expired or already been withdrawn. Ask your sponsor for a new invite.</p></CardContent></Card></main>;

  const { pilot } = participant.data;
  return <main className="min-h-screen bg-[#F8F5F0] text-[#1C1C1C]"><header className="border-b border-[#DCE3EA] bg-[#0A1A2F] text-white"><div className="mx-auto flex max-w-3xl items-center justify-between px-6 py-4"><a href="/" className="flex items-center gap-3"><img src="/logo.png" alt="LevelNext" className="h-9" /></a><span className="flex items-center gap-2 text-xs text-white/65"><LockKeyhole size={14} /> Private participant space</span></div></header><section className="mx-auto max-w-3xl px-6 pb-16 pt-12"><p className="text-xs font-bold uppercase tracking-[0.22em] text-[#A78418]">30-Day Behaviour Change Proof</p><h1 className="mt-3 text-4xl font-bold leading-tight text-[#0A1A2F]">This isn’t another course.</h1><p className="mt-4 text-lg leading-8 text-slate-600">Over the next 30 days, LevelNext will help you practise one to three behaviours in situations you are already dealing with at work. Most interactions take only a few minutes.</p><div className="mt-8 flex items-center gap-2">{[1, 2, 3, 4].map((item) => <div key={item} className={`h-2 flex-1 rounded-full ${item <= stage ? "bg-[#D4AF37]" : "bg-[#DCE3EA]"}`} />)}</div><Card className="mt-6 border-[#DCE3EA] bg-white shadow-[0_20px_60px_rgba(10,26,47,0.08)]"><CardHeader><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#A78418]">{stage === 1 ? "Start with your baseline" : stage === 2 ? "Try a Behaviour Rep" : stage === 3 ? "Bring it into real work" : "Help us see the movement"}</p><CardTitle className="mt-2 text-2xl text-[#0A1A2F]">{stage === 1 ? "What situation are you dealing with?" : stage === 2 ? "Practise the opening for your next moment." : stage === 3 ? "What did you do differently at work?" : "What are you noticing?"}</CardTitle></CardHeader><CardContent className="space-y-5">
    {stage === 1 && <><div className="rounded-lg bg-[#EEF4F9] p-4 text-sm leading-6 text-slate-700"><b>Your pilot focus:</b> {pilot.targetBehaviours.join(" · ")}<br /><span className="text-slate-500">{pilot.businessProblem}</span></div><label className="block"><span className="mb-2 block text-sm font-semibold text-[#0A1A2F]">Describe a current workplace situation</span><Textarea value={situation} onChange={(event) => setSituation(event.target.value)} placeholder="For example: I need to give a direct update on a missed commitment." className="min-h-32 border-[#C9D4DF]" /></label><label className="block"><span className="mb-2 block text-sm font-semibold text-[#0A1A2F]">What would you like to handle differently?</span><Textarea value={desiredMovement} onChange={(event) => setDesiredMovement(event.target.value)} placeholder="A clear opening, a specific ask, or a better ownership handoff." className="min-h-24 border-[#C9D4DF]" /></label><Button disabled={situation.trim().length < 8 || desiredMovement.trim().length < 8 || baseline.isPending} onClick={() => baseline.mutate({ token, currentSituation: situation, desiredMovement })} className="bg-[#D4AF37] text-[#0A1A2F]">Start my Behaviour Rep <ArrowRight size={16} /></Button></>}
    {stage === 2 && <><div className="rounded-lg border border-[#D4AF37]/40 bg-[#FFF8DF] p-5"><div className="flex items-center gap-3"><Sparkles className="text-[#A78418]" size={20} /><p className="text-sm leading-6 text-slate-700">Take 90 seconds. Say the first two sentences you would use in the situation you named. Focus on the observable facts, the impact, and the outcome you need.</p></div></div><label className="block"><span className="mb-2 block text-sm font-semibold text-[#0A1A2F]">Who are you practising with?</span><Textarea value={practiceRole} onChange={(event) => setPracticeRole(event.target.value)} placeholder="e.g. a direct report who missed the same deadline twice" className="min-h-28 border-[#C9D4DF]" /></label><Button disabled={practiceRole.trim().length < 2 || rep.isPending} onClick={() => rep.mutate({ token, practiceRole })} className="bg-[#D4AF37] text-[#0A1A2F]">Complete Behaviour Rep <Check size={16} /></Button></>}
    {stage === 3 && <><div className="rounded-lg bg-[#EEF4F9] p-4 text-sm leading-6 text-slate-700"><b>Use actual work as the classroom.</b> Record the action, not a polished reflection. Private coaching text is never shown to your sponsor.</div><label className="block"><span className="mb-2 block text-sm font-semibold text-[#0A1A2F]">What kind of moment was it?</span><input value={situationType} onChange={(event) => setSituationType(event.target.value)} placeholder="e.g. feedback, delegation, stakeholder update" className="h-11 w-full rounded-md border border-[#C9D4DF] px-3 text-sm" /></label><label className="block"><span className="mb-2 block text-sm font-semibold text-[#0A1A2F]">What action did you take?</span><Textarea value={actionTaken} onChange={(event) => setActionTaken(event.target.value)} placeholder="What did you say, do, or hand over?" className="min-h-28 border-[#C9D4DF]" /></label><label className="block"><span className="mb-2 block text-sm font-semibold text-[#0A1A2F]">What signal did you notice? <span className="font-normal text-slate-400">(optional)</span></span><Textarea value={outcomeSignal} onChange={(event) => setOutcomeSignal(event.target.value)} placeholder="e.g. the owner repeated back the outcome and next date" className="min-h-24 border-[#C9D4DF]" /></label><Button disabled={situationType.trim().length < 2 || actionTaken.trim().length < 8 || realWork.isPending} onClick={() => realWork.mutate({ token, situationType, actionTaken, outcomeSignal })} className="bg-[#D4AF37] text-[#0A1A2F]">Record real-work application <ArrowRight size={16} /></Button></>}
    {stage === 4 && <><div className="flex items-start gap-3 rounded-lg bg-[#EEF4F9] p-5"><MessageSquare className="mt-1 text-[#0A1A2F]" size={20} /><p className="text-sm leading-6 text-slate-700">You’ve completed the first loop: notice → choose → practise → do. If you are an observer, share only what you directly noticed.</p></div><div className="grid gap-3 sm:grid-cols-3">{([["not_yet", "Not yet"], ["early_signal", "Early signal"], ["consistent_signal", "Consistent signal"]] as const).map(([value, label]) => <button type="button" key={value} onClick={() => setMovement(value)} className={`rounded-lg border p-4 text-left text-sm font-semibold ${movement === value ? "border-[#D4AF37] bg-[#FFF8DF] text-[#0A1A2F]" : "border-[#DCE3EA] bg-white text-slate-700"}`}>{label}</button>)}</div><Button disabled={pulse.isPending} onClick={() => pulse.mutate({ token, movement })} className="bg-[#D4AF37] text-[#0A1A2F]">Save pulse <Check size={16} /></Button></>}
    {notice && <p className="text-sm font-medium text-emerald-700">{notice}</p>}
  </CardContent></Card><footer className="mt-6 flex items-start gap-2 text-xs leading-5 text-slate-500"><ShieldCheck size={14} className="mt-0.5 flex-shrink-0" /> Your personal coaching and reflection stay private. The sponsor sees approved aggregate evidence, not your reflection text.</footer></section></main>;
}
