import * as React from "react";
import { useEffect, useMemo, useState } from "react";
import { useLocation } from "wouter";
import { BarChart3, CheckCircle2, CircleAlert, FilePlus2, Loader2, ShieldCheck, XCircle } from "lucide-react";
import PlatformLayout from "@/components/PlatformLayout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";

const AGENT_LABELS = { self_leadership_intelligence: "Self-Leadership Intelligence", success_partner_nudges: "Success Partner Nudges" } as const;

export default function EngineeringPromptEvaluation() {
  const { user, isAuthenticated, loading } = useAuth();
  const [, navigate] = useLocation();
  const utils = trpc.useUtils();
  const [agentFilter, setAgentFilter] = useState<string>("all");
  const dashboard = trpc.engineeringAdmin.promptEvaluationDashboard.useQuery(agentFilter === "all" ? undefined : { agentCode: agentFilter as keyof typeof AGENT_LABELS }, { enabled: user?.role === "admin" });
  const createVersion = trpc.engineeringAdmin.createPromptVersion.useMutation({ onSuccess: () => utils.engineeringAdmin.promptEvaluationDashboard.invalidate() });
  const recordRun = trpc.engineeringAdmin.recordEvaluationRun.useMutation({ onSuccess: () => utils.engineeringAdmin.promptEvaluationDashboard.invalidate() });
  const [versionAgent, setVersionAgent] = useState<keyof typeof AGENT_LABELS>("self_leadership_intelligence");
  const [versionLabel, setVersionLabel] = useState("");
  const [modelId, setModelId] = useState("claude-sonnet-4-6");
  const [selectedVersionId, setSelectedVersionId] = useState<string>("");
  const [caseCode, setCaseCode] = useState("");
  const [status, setStatus] = useState<"passed" | "failed" | "blocked">("passed");
  const [score, setScore] = useState("90");
  const [failureReasons, setFailureReasons] = useState("");

  useEffect(() => { if (!loading && !isAuthenticated) navigate("/"); }, [isAuthenticated, loading, navigate]);
  const versions = dashboard.data?.versions ?? [];
  const totals = useMemo(() => versions.reduce((acc, version) => ({ total: acc.total + version.summary.total, passed: acc.passed + version.summary.passed, failed: acc.failed + version.summary.failed, blocked: acc.blocked + version.summary.blocked }), { total: 0, passed: 0, failed: 0, blocked: 0 }), [versions]);

  if (loading || (user?.role === "admin" && dashboard.isLoading)) return <PlatformLayout title="Prompt Evaluation"><div className="mx-auto max-w-6xl px-4 py-8 sm:px-6"><Skeleton className="h-12 w-80" /><Skeleton className="mt-8 h-96 rounded-3xl" /></div></PlatformLayout>;
  if (user?.role !== "admin") return <PlatformLayout title="Prompt Evaluation"><div className="mx-auto max-w-3xl px-4 py-16 text-center"><ShieldCheck className="mx-auto text-[#D4A900]" size={36} /><h1 className="mt-4 text-2xl font-bold text-[#10243E]">Platform administration required</h1><p className="mt-2 text-sm text-slate-600">Prompt evaluation evidence is restricted to platform administrators.</p></div></PlatformLayout>;

  return <PlatformLayout title="Prompt Evaluation"><main className="mx-auto max-w-6xl px-4 py-6 sm:px-6 sm:py-8">
    <div className="mb-7 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[0.18em] text-[#B58A00]">Engineering Intelligence</p><h1 className="mt-2 text-3xl font-bold text-[#10243E]">Prompt Evaluation Evidence</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">Track versioned evidence for the Self-Leadership and Success Partner agents before a prompt or model change is treated as release-ready.</p></div><Select value={agentFilter} onValueChange={setAgentFilter}><SelectTrigger className="w-full lg:w-72"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All agents</SelectItem><SelectItem value="self_leadership_intelligence">Self-Leadership Intelligence</SelectItem><SelectItem value="success_partner_nudges">Success Partner Nudges</SelectItem></SelectContent></Select></div>
    <div className="grid gap-3 sm:grid-cols-4">{[{ label: "Evaluation cases", value: totals.total, icon: BarChart3 }, { label: "Passed", value: totals.passed, icon: CheckCircle2 }, { label: "Failed", value: totals.failed, icon: XCircle }, { label: "Blocked", value: totals.blocked, icon: CircleAlert }].map((item) => { const Icon = item.icon; return <div key={item.label} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><Icon className="text-[#D4A900]" size={18} /><p className="mt-3 text-2xl font-bold text-[#10243E]">{item.value}</p><p className="text-xs text-slate-500">{item.label}</p></div>; })}</div>
    <div className="mt-6 grid gap-6 lg:grid-cols-[0.85fr_1.15fr]">
      <section className="space-y-6"><div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold text-[#10243E]">Register prompt version</h2><div className="mt-4 space-y-3"><div><Label>Agent</Label><Select value={versionAgent} onValueChange={(value) => setVersionAgent(value as keyof typeof AGENT_LABELS)}><SelectTrigger className="mt-1"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="self_leadership_intelligence">Self-Leadership Intelligence</SelectItem><SelectItem value="success_partner_nudges">Success Partner Nudges</SelectItem></SelectContent></Select></div><div><Label>Version label</Label><Input className="mt-1" value={versionLabel} onChange={(event) => setVersionLabel(event.target.value)} placeholder="e.g. self-leadership-v1.1" /></div><div><Label>Model</Label><Input className="mt-1" value={modelId} onChange={(event) => setModelId(event.target.value)} /></div><Button disabled={createVersion.isPending || versionLabel.trim().length < 3} onClick={() => createVersion.mutate({ agentCode: versionAgent, versionLabel, modelId, status: "candidate" })} className="w-full bg-[#10243E] text-white"><FilePlus2 className="mr-2" size={15} /> Register candidate</Button></div></div>
      <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold text-[#10243E]">Record evaluation evidence</h2><div className="mt-4 space-y-3"><div><Label>Prompt version</Label><Select value={selectedVersionId} onValueChange={setSelectedVersionId}><SelectTrigger className="mt-1"><SelectValue placeholder="Choose a version" /></SelectTrigger><SelectContent>{versions.map((version) => <SelectItem key={version.id} value={String(version.id)}>{version.versionLabel} · {version.modelId}</SelectItem>)}</SelectContent></Select></div><div><Label>Case code</Label><Input className="mt-1" value={caseCode} onChange={(event) => setCaseCode(event.target.value)} placeholder="e.g. privacy_boundary_01" /></div><div className="grid grid-cols-2 gap-3"><div><Label>Status</Label><Select value={status} onValueChange={(value) => setStatus(value as typeof status)}><SelectTrigger className="mt-1"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="passed">Passed</SelectItem><SelectItem value="failed">Failed</SelectItem><SelectItem value="blocked">Blocked</SelectItem></SelectContent></Select></div><div><Label>Score</Label><Input className="mt-1" type="number" min="0" max="100" value={score} onChange={(event) => setScore(event.target.value)} /></div></div><div><Label>Failure reasons <span className="font-normal text-slate-400">Comma-separated, optional</span></Label><Input className="mt-1" value={failureReasons} onChange={(event) => setFailureReasons(event.target.value)} /></div><Button disabled={recordRun.isPending || !selectedVersionId || caseCode.trim().length < 2} onClick={() => recordRun.mutate({ promptVersionId: Number(selectedVersionId), caseCode, status, score: Number(score), failureReasons: failureReasons.split(",").map((item) => item.trim()).filter(Boolean) })} className="w-full bg-[#10243E] text-white">{recordRun.isPending && <Loader2 className="mr-2 animate-spin" size={15} />} Save evidence</Button></div></div></section>
      <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold text-[#10243E]">Version evidence</h2><div className="mt-5 space-y-4">{versions.length ? versions.map((version) => <article key={version.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-sm font-bold text-[#10243E]">{version.versionLabel}</p><p className="mt-1 text-xs text-slate-500">{AGENT_LABELS[version.agentCode]} · {version.modelId}</p></div><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold uppercase tracking-[0.1em] ${version.summary.releaseGate === "eligible" ? "bg-emerald-50 text-emerald-700" : version.summary.releaseGate === "blocked" ? "bg-red-50 text-red-700" : "bg-amber-50 text-amber-700"}`}>{version.summary.releaseGate.replace(/_/g, " ")}</span></div><div className="mt-4"><div className="mb-1 flex justify-between text-xs text-slate-500"><span>{version.summary.passed}/{version.summary.total} passed</span><span>{version.summary.passRate}%</span></div><div className="h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-emerald-500" style={{ width: `${version.summary.passRate}%` }} /></div></div><div className="mt-4 space-y-2">{version.runs.slice(0, 4).map((run) => <div key={run.id} className="rounded-xl bg-slate-50 p-3"><div className="flex items-center justify-between gap-3"><p className="text-xs font-semibold text-[#10243E]">{run.caseCode}</p><span className={`text-[10px] font-bold uppercase ${run.status === "passed" ? "text-emerald-700" : run.status === "failed" ? "text-red-700" : "text-amber-700"}`}>{run.status}</span></div><p className="mt-1 text-[11px] text-slate-500">Score {run.score}/100 · {new Date(run.createdAt).toLocaleDateString("en-IN", { day: "numeric", month: "short" })}</p>{run.failureReasons.length > 0 && <p className="mt-1 text-[11px] text-red-700">{run.failureReasons.join("; ")}</p>}</div>)}{version.runs.length === 0 && <p className="rounded-xl border border-dashed border-slate-200 p-4 text-xs text-slate-500">No evaluation evidence recorded yet.</p>}</div></article>) : <div className="rounded-2xl border border-dashed border-slate-300 p-8 text-center text-sm text-slate-500">Register a prompt version to begin collecting release evidence.</div>}</div></section>
    </div>
  </main></PlatformLayout>;
}
