export interface AcademySeedKnowledge {
  objectType: "thesis" | "product_family" | "product" | "engine" | "golden_journey" | "misconception";
  slug: string;
  title: string;
  summary: string;
  disclosureBand: "need_now" | "recognize" | "later";
  productCode?: string;
  roleRelevance: string[];
  content: Record<string, unknown>;
}

export const ACADEMY_SEED_KNOWLEDGE: AcademySeedKnowledge[] = [
  {
    objectType: "thesis",
    slug: "levelnext-change-thesis",
    title: "The LevelNext Change Loop",
    summary: "Work changes when people see their reality clearly, practise high-stakes moments safely, and produce observable evidence in real work.",
    disclosureBand: "need_now",
    roleRelevance: ["all"],
    content: {
      howToUnderstand: "Use this section as the 'why' behind every LevelNext product. If you remember only one idea, remember that insight becomes useful only when it changes a real moment at work.",
      definitions: {
        "Change loop": "The repeatable path from seeing a gap to practising and proving a new behaviour.",
        "Real-work evidence": "An observable change in a meeting, decision, conversation, or commitment—not a completed lesson.",
      },
      tooltips: {
        corePrinciple: "The sequence LevelNext uses to turn insight into action.",
        whyWorkshopFails: "The reason awareness alone does not reliably change behaviour under pressure.",
      },
      corePrinciple: "Diagnose → Understand → Practise → Act → Reflect → Evidence → Adapt",
      whyWorkshopFails: "Workshops transfer conceptual awareness. Under pressure, professionals default to legacy emotional habits unless they have rehearsed the specific move and made accountability visible.",
      outcome: "Capability becomes visible in the work rather than remaining trapped in a feedback report.",
    },
  },
  {
    objectType: "product_family",
    slug: "product-family-leadership-core",
    title: "Leadership & Transition Intelligence",
    summary: "Diagnostics, practice, and behavioural moves tailored to the exact transition stage of the individual.",
    disclosureBand: "need_now",
    roleRelevance: ["all"],
    content: {
      howToUnderstand: "Read this as the LevelNext progression map. Start with the person's transition stage, then choose the product that addresses the behavioural demands of that stage—not the most senior-sounding product.",
      definitions: {
        "Transition stage": "The shift in scope, identity, and expectations a person is navigating, such as becoming a manager or enterprise leader.",
        "Product family": "A group of connected LevelNext experiences designed for a specific leadership or career transition.",
        "Behavioural move": "A small, observable action or phrase that changes what happens in a high-stakes moment.",
      },
      tooltips: {
        tiers: "Each card represents a transition audience and the most relevant starting experience.",
        targetPersonas: "The people most likely to benefit from this tier—not a restriction on who may use it.",
        primaryDerailers: "Predictable overused strengths or avoidance patterns that can block progress at this transition.",
        recommendedBehaviouralMoves: "Specific behaviours to practise after the diagnostic identifies a gap.",
      },
      tiers: [
        {
          code: "early_career",
          label: "Early Career Intelligence",
          focus: "First critical years of ownership, communication, and risk visibility",
          route: "/early-career",
          primaryDerailers: ["Waiting for permission", "Hiding uncertainty until the deadline", "Confusing activity with ownership"],
          targetPersonas: ["Early-career professionals", "Graduate hires", "Individual contributors in their first major role"],
          recommendedBehaviouralMoves: ["Make the first clear ask", "Surface risk before it becomes urgent", "Close the loop with an evidence update"],
          howToUse: "Start here when the person is building professional judgement and visibility for the first time.",
        },
        {
          code: "pe",
          label: "Professional Intelligence (PEI)",
          focus: "Critical individual contributors moving work forward with less manager intervention",
          route: "/pe",
          primaryDerailers: ["Over-relying on technical expertise", "Solving alone instead of influencing", "Escalating problems without a recommendation"],
          targetPersonas: ["Experienced individual contributors", "Project and functional specialists", "Professionals preparing for broader scope"],
          recommendedBehaviouralMoves: ["Frame the decision before giving the detail", "Make a recommendation with trade-offs", "Build the stakeholder relationship before the ask"],
          howToUse: "Choose PEI when the person must move from dependable execution to visible judgement and influence.",
        },
        {
          code: "mep",
          label: "Manager Effectiveness (MEP)",
          focus: "First-time and scaling managers shifting from doing to enabling, delegation, and coaching",
          route: "/manager",
          primaryDerailers: ["Rescuing instead of delegating", "Avoiding accountability conversations", "Becoming the team's bottleneck"],
          targetPersonas: ["First-time managers", "Engineering and functional managers", "Managers scaling from one team to several"],
          recommendedBehaviouralMoves: ["Contract clarity before escalation", "Ask before advising", "Delegate the outcome—not just the task"],
          howToUse: "Use MEP when performance depends on how the manager creates ownership in other people.",
        },
        {
          code: "ldi",
          label: "Leader Intelligence (LDI / LII)",
          focus: "Senior leaders shaping strategic influence, enterprise alignment, and derailment resilience",
          route: "/li-report/LDI/demo",
          primaryDerailers: ["Driving outcomes directly when coalition is required", "Being strategically right but relationally isolated", "Under-communicating the narrative behind a decision"],
          targetPersonas: ["Directors and business-unit heads", "GCC and enterprise leaders", "Senior leaders in cross-functional transformation"],
          recommendedBehaviouralMoves: ["Build the coalition before the decision forum", "Name the enterprise trade-off", "Create dissent that remains safe to act on"],
          howToUse: "Choose LDI when the leader's impact depends on enterprise influence, not only functional authority.",
        },
        {
          code: "executive",
          label: "Executive Intelligence (ECI)",
          focus: "Board-level presence, high-stakes communication, and executive decision outcomes",
          route: "/executive",
          primaryDerailers: ["Over-explaining instead of landing the decision", "Using certainty to cover unresolved risk", "Treating executive communication as presentation rather than influence"],
          targetPersonas: ["Executives and C-suite leaders", "Board-facing functional heads", "Leaders entering enterprise-wide visibility"],
          recommendedBehaviouralMoves: ["Lead with the decision and its consequence", "Make the risk discussable", "Turn the narrative into a clear stakeholder commitment"],
          howToUse: "Use ECI when communication quality directly affects executive trust, decisions, and enterprise momentum.",
        },
      ],
    },
  },
  {
    objectType: "product",
    slug: "product-mep",
    title: "Manager Effectiveness Platform (MEP)",
    summary: "Turns managerial capability gaps into targeted behavioural moves, voice simulator rehearsals, and real-work commitments.",
    disclosureBand: "need_now",
    productCode: "MEP",
    roleRelevance: ["all"],
    content: {
      howToUnderstand: "Think of MEP as a manager's operating layer: it helps the manager notice the moment where ownership breaks down, practise a better response, and carry that response into the next conversation.",
      definitions: {
        "Manager effectiveness": "The ability to create clarity, ownership, feedback, and progress through other people.",
        "Practice partner": "The guided AI role-play that lets a manager rehearse a difficult conversation before the real meeting.",
      },
      tooltips: {
        keyComponents: "These are the connected experiences that move a manager from diagnosis to evidence.",
        whyLayer: "The underlying behavioural reason the product matters—not just a feature description.",
      },
      whoItIsFor: "First-time managers, engineering managers, and people leaders stepping into team accountability.",
      problemSolved: "Managers get promoted for functional excellence, then struggle with delegation, feedback avoidance, and priority drag.",
      userExperience: "Role-context diagnostic → Behavioural breakthrough moment → Move selection → Voice simulation rehearsal → Real-work commitment → Team evidence.",
      route: "/manager",
      keyComponents: ["Manager Diagnostics", "Behavioural Move Studio", "Voice Practice Simulator", "Manager Brief", "Team Commitments"],
      whyLayer: "A manager does not fail from lack of intention; they fail at the micro-moment of a difficult conversation. Rehearsing verbatim phrases builds muscle memory before the meeting.",
    },
  },
  {
    objectType: "product",
    slug: "product-ldi",
    title: "Leader Derailment Intelligence (LDI / LII)",
    summary: "Exposes derailment risks, blind spots, and enterprise leverage points before they impact reputation or scale.",
    disclosureBand: "need_now",
    productCode: "LDI",
    roleRelevance: ["all"],
    content: {
      howToUnderstand: "LDI is not a scorecard to admire. Read it as an early-warning system: it shows where a leader's familiar strength may become a liability at enterprise scale and what to practise next.",
      definitions: {
        "Derailer": "A strength, habit, or emotional pattern that becomes counterproductive when the context or scale changes.",
        "Enterprise leverage": "The ability to create outcomes through alignment, narrative, and influence beyond one's direct reporting line.",
      },
      tooltips: {
        keyComponents: "The surfaces that turn a leadership diagnostic into reflection, practice, and action.",
        whyLayer: "The leadership context that explains why the same behaviour can help in one role and derail in another.",
      },
      whoItIsFor: "Directors, Business Unit heads, and senior leaders carrying cross-functional scope.",
      problemSolved: "Leaders stall when their historic strength (e.g. driving results directly) becomes a derailer in an executive ecosystem requiring coalition and narrative alignment.",
      userExperience: "Diagnostic assessment → Strategic scorecards → Derailment risk radar → Guided Mirror reflection → Breakthrough Behavioural Move → Sponsor progress heatmap.",
      route: "/li-report/LDI/demo",
      keyComponents: ["Leadership Graph", "Derailment Archetypes", "Strategic Communicator Scorecard", "Behavioural Breakthrough Studio"],
      whyLayer: "Executive failure is rarely technical; it is nearly always relational, political, or narrative. LDI makes the hidden edge visible before a derailment occurs.",
    },
  },
  {
    objectType: "engine",
    slug: "engine-behavioural-intelligence",
    title: "Behavioural Intelligence Engine™",
    summary: "The shared core engine across LevelNext that turns diagnostic insight into observable behavioural moves, voice rehearsal, and anonymized aggregate progress.",
    disclosureBand: "need_now",
    roleRelevance: ["all"],
    content: {
      howToUnderstand: "This is the shared engine underneath multiple LevelNext applications. It is the bridge between 'I understand my gap' and 'I behaved differently in a real moment'.",
      definitions: {
        "Behavioural moment": "A specific workplace interaction where a different response could change the outcome.",
        "Evidence ledger": "A private record of practice, commitments, and reflections that shows movement over time.",
      },
      tooltips: {
        stages: "The reusable sequence every connected application can use to turn insight into practice.",
        diagnostics: "These are the platform's diagnostic entry points. Each one makes a different kind of capability, risk, or readiness visible before practice begins.",
        connectedProducts: "These applications use the Behavioural Intelligence Engine to turn their diagnostic insight into practice and evidence.",
        underlyingEngines: "These engines run behind the screens. They interpret signals, protect boundaries, connect insight to practice, and help LevelNext stay useful without exposing private data.",
        privacyGuarantee: "The rule that protects individual moments while allowing safe aggregate sponsor insight.",
      },
      layer: "Core Platform Engine",
      stages: [
        {
          label: "Moment Capture",
          whatItMeans: "Name the specific workplace moment where progress is stuck or a different response could change the outcome.",
          example: "A manager notices they keep postponing a direct performance conversation with a team member.",
          output: "A private, concrete behavioural moment with enough context to work on—not a vague goal such as 'be a better leader'.",
        },
        {
          label: "Breakthrough Analysis",
          whatItMeans: "Understand the pattern underneath the moment: what the person is doing, avoiding, overusing, or assuming.",
          example: "The analysis distinguishes accountability avoidance from a genuine lack of information or authority.",
          output: "A clear explanation of the current pattern and the leverage point where a small change can create movement.",
        },
        {
          label: "Behavioural Moves",
          whatItMeans: "Choose a small, observable action or phrase that replaces the old pattern in the next real interaction.",
          example: "Use 'Can we agree what success looks like by Friday?' instead of leaving expectations implied.",
          output: "One or more specific moves that can be seen, heard, and practised—not abstract advice.",
        },
        {
          label: "Practice Links",
          whatItMeans: "Connect the selected move to a rehearsal, simulator, coach prompt, or guided reflection before the real moment.",
          example: "The manager role-plays the conversation with the Voice Simulator and repeats the phrase until it feels natural.",
          output: "A linked practice activity that turns understanding into readiness under realistic pressure.",
        },
        {
          label: "Actions & Evidence",
          whatItMeans: "Carry the move into real work, then record what was attempted and what changed in the conversation, decision, or commitment.",
          example: "After the 1:1, the manager records the agreed sprint commitments and the next review date.",
          output: "A private evidence record showing application in the workplace, not just completion of a learning activity.",
        },
        {
          label: "Reflections",
          whatItMeans: "Look back on the attempt to identify what shifted, what remains difficult, and what to repeat or adapt next time.",
          example: "The manager notices that naming the expectation early reduced tension and decides to use the same move in another conversation.",
          output: "A learning signal that improves the next behavioural attempt and makes progress visible over time.",
        },
      ],
      underlyingEngines: [
        {
          label: "Intelligence Core",
          layer: "Platform foundation",
          whatItDoes: "Registers the intelligence modules, applies approved judgement rules, and coordinates shared context across products.",
          inTheBackground: "When a diagnostic or product event completes, the core decides which rules, context, and downstream intelligence are allowed to run.",
          learnerBenefit: "You get a connected experience instead of separate assessments that do not learn from one another.",
          guardrail: "Uses explicit module contracts, tenant boundaries, and audit events rather than silently sharing everything.",
        },
        {
          label: "Behavioural Intelligence Engine",
          layer: "Practice and evidence layer",
          whatItDoes: "Turns an insight into a specific behavioural move, rehearsal, real-work action, evidence record, and reflection.",
          inTheBackground: "It connects moments from MEP, LDI, and other applications to move suggestions, voice practice, phrase telemetry, and progress signals.",
          learnerBenefit: "You can move from knowing what to improve to practising what to say or do next.",
          guardrail: "Individual moments and reflections stay private; sponsor views use anonymised aggregates with a 5+ threshold.",
        },
        {
          label: "Ontology and Distinction Engine",
          layer: "Reasoning layer",
          whatItDoes: "Separates what happened, what was observed, what was interpreted, what action was taken, and what result followed.",
          inTheBackground: "The Universal Ontological Distinction Library helps the system choose a proportionate coaching question instead of jumping to a judgement about a person.",
          learnerBenefit: "You get clearer reflection and more useful next actions without being reduced to a label.",
          guardrail: "Motives remain hypotheses, structural constraints are not reframed as mindset problems, and the shallowest useful reasoning depth is preferred.",
        },
        {
          label: "Narrative Intelligence Engine",
          layer: "Meaning-making layer",
          whatItDoes: "Translates diagnostic patterns into tentative hypotheses, stories, questions, and language that a leader can examine.",
          inTheBackground: "It links scores and leadership stage to possible patterns while keeping the interpretation explicitly developmental rather than definitive.",
          learnerBenefit: "You can understand why a result may matter in a real conversation, decision, or transition.",
          guardrail: "Narratives are hypotheses to test, not diagnoses or fixed descriptions of identity.",
        },
        {
          label: "Leadership Graph Engine",
          layer: "Profile continuity layer",
          whatItDoes: "Maintains the evolving relationship between completed diagnostics, scores, zones, archetypes, and development edges.",
          inTheBackground: "When a module is completed, it updates the person’s connected Leadership Graph so later experiences can use the right context.",
          learnerBenefit: "Your LevelNext journey becomes a growing profile rather than a collection of disconnected reports.",
          guardrail: "Only authorised profile context is used, with access controls around participant, coach, organisation, and admin views.",
        },
        {
          label: "Executive Intelligence Engine",
          layer: "Executive decision layer",
          whatItDoes: "Supports high-stakes communication, decision review, executive presence, and strategic judgement.",
          inTheBackground: "It combines executive context, diagnostic signals, decision outcomes, and review prompts to help leaders prepare and learn from consequential moments.",
          learnerBenefit: "You can rehearse board-level and stakeholder conversations with more clarity and composure.",
          guardrail: "It supports judgement; it does not make employment, promotion, legal, medical, or financial decisions for people.",
        },
        {
          label: "Self-Leadership Intelligence Engine",
          layer: "Individual development layer",
          whatItDoes: "Interprets self-leadership patterns across career stage, agency, ownership, and personal operating choices.",
          inTheBackground: "It powers guided mirrors and career-stage prompts that connect self-observation to a practical experiment.",
          learnerBenefit: "You receive development questions that fit the transition you are actually navigating.",
          guardrail: "It is developmental coaching support, not a personality diagnosis or a claim about fixed potential.",
        },
        {
          label: "Engineering Intelligence Engine",
          layer: "Technical population layer",
          whatItDoes: "Builds an operating profile for technical professionals across collaboration, systems thinking, business context, and human–AI judgement.",
          inTheBackground: "It scores engineering diagnostic responses, creates missions, and supports privacy-bounded Success Partner nudges for organisation cohorts.",
          learnerBenefit: "Technical development is connected to real engineering work rather than generic leadership content.",
          guardrail: "Partner nudges use only permitted workflow facts and never expose private reflections or diagnostic answers.",
        },
        {
          label: "Critical Thinking Engine",
          layer: "Decision-quality layer",
          whatItDoes: "Structures how people frame problems, question assumptions, inspect evidence, compare options, decide, and learn.",
          inTheBackground: "It combines individual and environment responses into developmental feedback on decision practices.",
          learnerBenefit: "You can see where a decision process needs strengthening before a high-cost mistake occurs.",
          guardrail: "It is not an intelligence test, psychometric label, selection tool, performance ranking, or disciplinary instrument.",
        },
        {
          label: "Practice and Voice Simulator Engine",
          layer: "Rehearsal layer",
          whatItDoes: "Creates realistic role-play conversations so a learner can practise a behavioural move, hear it aloud, and receive targeted feedback.",
          inTheBackground: "It carries the selected move and verbatim phrases into a session, tracks keyed phrase use without storing the target phrases as raw telemetry, and links completion back to evidence.",
          learnerBenefit: "You can rehearse under realistic pressure before trying the conversation at work.",
          guardrail: "Practice data is scoped to the learner’s session and linked Behavioural Intelligence record.",
        },
        {
          label: "Sales and Pipeline Intelligence Engine",
          layer: "Commercial application layer",
          whatItDoes: "Finds behavioural signals in sales work such as stalled opportunities, silence, risk, and next-action quality.",
          inTheBackground: "It combines opportunity context with deterministic signal rules and practice prompts to help a seller choose the next useful move.",
          learnerBenefit: "Commercial coaching can focus on an actual deal or conversation rather than generic selling advice.",
          guardrail: "Signals are coaching aids and should not be treated as covert employee surveillance or definitive intent detection.",
        },
        {
          label: "Success Partner Nudge Engine",
          layer: "Human support layer",
          whatItDoes: "Drafts concise, editable nudges that help a human Success Partner decide when and how to invite a useful next conversation.",
          inTheBackground: "It ranks only permitted workflow candidates and grounds each suggested question in supplied facts rather than inventing motivation or private circumstances.",
          learnerBenefit: "Human support arrives with better timing while remaining human-led and editable.",
          guardrail: "It is not a surveillance, ranking, performance, motivation, personality, or mental-state engine.",
        },
        {
          label: "Career Opportunity and Relationship Intelligence",
          layer: "Career transition layer",
          whatItDoes: "Maps career access, market signals, relationships, and next actions into a practical opportunity journey.",
          inTheBackground: "It helps transform career context into positioning, access paths, relationship actions, and preparation—not just a static career score.",
          learnerBenefit: "You can connect a career insight to a specific conversation, opportunity, or visibility action.",
          guardrail: "Recommendations are exploratory and user-directed; they do not guarantee outcomes or make hiring decisions.",
        },
      ],
      diagnostics: [
        { label: "Executive Communication Intelligence", code: "ECI", audience: "Executives and board-facing leaders", focus: "Executive presence, narrative authority, listening, and communication under pressure.", route: "/diagnostics/eci" },
        { label: "Leadership Influence & Navigation Intelligence", code: "LII", audience: "Senior leaders working across stakeholders", focus: "Trust capital, coalition building, decision influence, and organisational navigation.", route: "/diagnostics/lii" },
        { label: "Leadership Derailment Intelligence", code: "LDI", audience: "Directors, business-unit heads, and senior leaders", focus: "Hidden leadership patterns that can become derailers at greater scale.", route: "/diagnostics/ldi" },
        { label: "Strategic Thinking Intelligence", code: "STI", audience: "Leaders responsible for strategic choices", focus: "Strategic clarity, systems thinking, business acumen, prioritisation, and decision quality.", route: "/diagnostics/sti" },
        { label: "GCC Readiness", code: "GCC", audience: "GCC and organisation leadership teams", focus: "Strategic influence, operating excellence, leadership and talent, innovation and AI, and enterprise alignment.", route: "/diagnostics/gcc", status: "Coming soon" },
        { label: "Career Positioning Intelligence", code: "CPI", audience: "Professionals navigating career identity and visibility", focus: "Career identity, market positioning, differentiation, and professional narrative.", route: "/diagnostics/cpi" },
        { label: "Career Marketability & Optionality Intelligence", code: "CMK", audience: "Professionals building career resilience", focus: "External visibility, skill relevance, network strength, mobility, and career options.", route: "/diagnostics/cmk" },
        { label: "AI Readiness Intelligence", code: "AIR", audience: "Professionals and leaders working with AI", focus: "AI literacy, workflow integration, strategic use of AI, and AI-augmented leadership.", route: "/diagnostics/air" },
        { label: "Engineering Intelligence", code: "ENG", audience: "Technical professionals and engineering leaders", focus: "Self-leadership, collaboration, problem framing, systems thinking, business context, and human–AI judgement.", route: "/engineering/diagnostic" },
        { label: "Manager Effectiveness Diagnostic", code: "MEP", audience: "First-time and scaling managers", focus: "Delegation, accountability, coaching, priority clarity, and creating ownership through others.", route: "/manager/diagnostics" },
        { label: "Professional Intelligence Assessment", code: "PEI", audience: "Individual contributors and experienced professionals", focus: "Ownership, judgement, execution, influence, and moving work forward with less manager intervention.", route: "/pe/assessment" },
        { label: "Early Career Intelligence Diagnostic", code: "ECI-Career", audience: "Early-career professionals and graduate hires", focus: "Professional ownership, communication, visibility, relationships, and early career judgement.", route: "/early-career/diagnostic" },
        { label: "Critical Thinking Index", code: "CTI", audience: "Teams and leaders making complex decisions", focus: "Critical thinking, decision quality, and the ability to examine assumptions in real work.", route: "/critical-thinking" },
        { label: "LevelNext Product Fluency Diagnostic", code: "ACADEMY", audience: "LevelNext team members and internal learners", focus: "Understanding the platform, navigating products, applying interventions, and explaining the change clearly.", route: "/academy/diagnostic" },
      ],
      privacyGuarantee: "HR sponsors view aggregate heatmaps only when cohorts meet or exceed 5 contributors. Individual reflections and moments remain private.",
      connectedProducts: ["Manager Effectiveness", "Leader Intelligence", "Early Career Intelligence", "Executive Intelligence", "Tech Intelligence", "Professional Intelligence"],
    },
  },
  {
    objectType: "golden_journey",
    slug: "golden-journey-first-time-manager",
    title: "Golden Journey: The First-Time Manager",
    summary: "How an engineering lead avoids a difficult performance conversation, discovers the blind spot in MEP, rehearses the move in the voice simulator, and completes the real meeting.",
    disclosureBand: "need_now",
    productCode: "MEP",
    roleRelevance: ["all"],
    content: {
      howToUnderstand: "Follow this story in sequence. It demonstrates how a LevelNext user moves from a hidden workplace tension to a diagnostic insight, a rehearsed phrase, and an observable commitment.",
      definitions: {
        "Golden journey": "A representative end-to-end story showing how a person experiences LevelNext in the flow of work.",
        "Breakthrough moment": "The point where the person can name the behaviour that is blocking progress and choose a different move.",
      },
      tooltips: {
        breakthroughMoment: "The diagnostic-to-practice handoff—the most important transition in the story.",
        realWorkShift: "The evidence that the learning reached an actual workplace conversation or decision.",
      },
      protagonist: "Aarav, Senior Lead transitioning to Engineering Manager",
      tension: "Avoids confronting a senior individual contributor missing sprints, fearing friction.",
      breakthroughMoment: "MEP diagnostic highlights Accountability Avoidance. Behavioural Intelligence proposes Move: 'Contracting Clarity Before Escalation'.",
      rehearsal: "Aarav practices verbatim phrasing in the LevelNext Voice Simulator with immediate spoken encouragement.",
      realWorkShift: "Conducts the 1:1 on Thursday; commits an evidence record showing agreement on revised sprint commitments.",
    },
  },
  {
    objectType: "misconception",
    slug: "misconception-feature-dump",
    title: "Misconception: LevelNext is a Content Library / LMS",
    summary: "LevelNext is not a library of courses to complete; it is an intelligence and practice loop embedded directly in workplace moments.",
    disclosureBand: "need_now",
    roleRelevance: ["all"],
    content: {
      howToUnderstand: "Use this section when explaining the difference between LevelNext and conventional learning platforms. Lead with the workplace problem and behaviour change, not the feature list.",
      definitions: {
        "Feature dump": "Listing capabilities without explaining the problem, user, or behaviour each capability changes.",
        "Embedded practice": "Rehearsal connected to a real upcoming conversation, decision, or commitment.",
      },
      tooltips: {
        triggerPhrases: "Words that often signal someone is interpreting LevelNext as passive courseware.",
        correction: "The concise explanation that repositions LevelNext as an intelligence and action platform.",
      },
      triggerPhrases: ["LMS", "online courses", "video modules", "learning catalogue"],
      correction: "LevelNext provides context-aware diagnostics, behavioural move generation, AI voice rehearsal, and real-work evidence. It measures change in the work, not video watch-time.",
    },
  },
];
