import { useEffect, useState } from "react";
import { AIChatBox, type Message } from "@/components/AIChatBox";
import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";

export default function EarlyCareerPractice() {
  const { isAuthenticated } = useAuth();
  const [sessionId, setSessionId] = useState<number | null>(null); const [feedback, setFeedback] = useState<any>(null); const [localMessages, setLocalMessages] = useState<Message[]>([]); const [error, setError] = useState<string | null>(null); const [lastScenario, setLastScenario] = useState<string | null>(null); const [lastMessage, setLastMessage] = useState<string | null>(null);
  const scenarios = trpc.earlyCareer.getPracticeScenarios.useQuery(undefined, { enabled: isAuthenticated });
  const start = trpc.earlyCareer.startPracticeSession.useMutation({ onSuccess: (data) => { setError(null); setSessionId(data.sessionId); }, onError: (e) => setError(e.message) });
  const send = trpc.earlyCareer.sendPracticeMessage.useMutation();
  const end = trpc.earlyCareer.endPracticeSession.useMutation({ onSuccess: (data) => { setError(null); setFeedback(data); }, onError: (e) => setError(e.message) });
  useEffect(() => { if (start.data?.opening) setLocalMessages([{ role: "assistant", content: start.data.opening }]); }, [start.data?.opening]);
  if (!isAuthenticated) return <div className="mx-auto max-w-3xl px-4 py-20 text-center text-[#56616D]">Sign in to practise a workplace conversation.</div>;
  const retry = () => { if (!sessionId && lastScenario) start.mutate({ scenarioId: lastScenario, difficulty: "realistic" }); else if (sessionId && lastMessage) submit(lastMessage); else if (sessionId) end.mutate({ sessionId }); };
  const submit = (content: string) => { if (!sessionId) return; setLastMessage(content); setError(null); setLocalMessages((current) => [...current, { role: "user", content }]); send.mutate({ sessionId, message: content }, { onSuccess: (data) => setLocalMessages((current) => [...current, { role: "assistant", content: data.reply }]), onError: (e) => { setLocalMessages((current) => current.slice(0, -1)); setError(e.message); } }); };
  const scenarioContent = scenarios.isLoading ? <div className="mt-6 rounded-xl border bg-white p-5 text-sm text-[#56616D]" style={{ borderColor: "#E1D9CE" }}>Loading rehearsal scenarios…</div> : scenarios.isError ? <div className="mt-6 rounded-xl bg-[#FBE9E7] p-4 text-sm text-[#8E2C1D]">Scenarios could not load. <button className="underline" onClick={() => scenarios.refetch()}>Retry</button></div> : !scenarios.data?.length ? <div className="mt-6 rounded-xl border bg-white p-5 text-sm text-[#56616D]" style={{ borderColor: "#E1D9CE" }}>No rehearsal scenarios are available for this programme yet. Ask your programme owner to add one, then refresh this page.</div> : <div className="mt-7 grid gap-4 md:grid-cols-2">{scenarios.data.map((scenario) => <button key={scenario.id} disabled={start.isPending} onClick={() => { setLastScenario(scenario.id); start.mutate({ scenarioId: scenario.id, difficulty: "realistic" }); }} className="rounded-2xl border bg-white p-5 text-left hover:bg-[#F8F5F0] disabled:opacity-60" style={{ borderColor: "#E1D9CE" }}><p className="text-xs font-semibold text-[#A47618]">{scenario.capabilityId.replaceAll("_", " ")}</p><h2 className="mt-2 font-semibold text-[#0A1A2F]">{scenario.title}</h2><p className="mt-2 text-sm leading-6 text-[#56616D]">{scenario.situation}</p></button>)}</div>;
  if (!sessionId) return <div className="mx-auto max-w-5xl px-4 py-8 md:px-8"><p className="text-xs font-semibold uppercase tracking-widest text-[#A47618]">Practice Partner</p><h1 className="mt-2 text-3xl font-semibold text-[#0A1A2F]">Rehearse before the real conversation.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#56616D]">This is a private developmental rehearsal, not a performance assessment.</p>{error && <div className="mt-4 rounded-xl bg-[#FBE9E7] p-3 text-sm text-[#8E2C1D]">{error} <button className="underline" onClick={retry}>Try again</button></div>}{scenarioContent}</div>;
  return <div className="mx-auto max-w-4xl px-4 py-8 md:px-8">{feedback ? <div className="rounded-2xl border bg-white p-7" style={{ borderColor: "#E1D9CE" }}><p className="text-xs font-semibold uppercase tracking-widest text-[#A47618]">Practice debrief</p><h1 className="mt-2 text-2xl font-semibold text-[#0A1A2F]">{feedback.headline}</h1><p className="mt-5 text-sm leading-6 text-[#56616D]">{feedback.tryNext}</p><p className="mt-4 text-sm italic text-[#56616D]">{feedback.reflectionQuestion}</p><Button className="mt-6" onClick={() => { setSessionId(null); setFeedback(null); setLocalMessages([]); }}>Choose another rehearsal</Button></div> : <>{error && <div className="mb-3 rounded-xl bg-[#FBE9E7] p-3 text-sm text-[#8E2C1D]">{error} <button className="underline" onClick={retry}>Try again</button></div>}<AIChatBox messages={localMessages} onSendMessage={submit} isLoading={send.isPending} height="590px" placeholder="Respond as you would in the real conversation…" /><Button className="mt-5" onClick={() => { setError(null); end.mutate({ sessionId }); }} disabled={end.isPending} style={{ background: "#0A1A2F", color: "#F8F5F0" }}>{end.isPending ? "Preparing debrief…" : "End practice and reflect"}</Button></>}</div>;
}
