import { useMemo, useState } from "react";
import { CheckCircle2, ClipboardCheck, LockKeyhole, RotateCcw, Sparkles } from "lucide-react";
import { Link } from "wouter";
import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";

export default function EarlyCareerDiagnostic() {
  const { isAuthenticated, loading: authLoading } = useAuth();
  const utils = trpc.useUtils();
  const diagnostic = trpc.earlyCareer.getDiagnostic.useQuery(undefined, { enabled: isAuthenticated });
  const [sessionId, setSessionId] = useState<number | null>(null);
  const [responses, setResponses] = useState<Record<string, number>>({});
  const [completedResult, setCompletedResult] = useState<any>(null);
  const [flowError, setFlowError] = useState<string | null>(null);
  const [retryResponse, setRetryResponse] = useState<{ sessionId: number; questionId: string; response: number } | null>(null);
  const start = trpc.earlyCareer.startDiagnostic.useMutation({
    onSuccess: (data) => { setFlowError(null); setSessionId(data.sessionId); setResponses(data.responses as Record<string, number>); utils.earlyCareer.getDiagnostic.invalidate(); },
    onError: (error) => { setFlowError(error.message || "We could not start the diagnostic."); toast.error("We could not start the diagnostic."); },
  });
  const submit = trpc.earlyCareer.submitDiagnosticResponse.useMutation({
    onSuccess: (data, variables) => { setFlowError(null); setRetryResponse(null); setResponses((current) => ({ ...current, [variables.questionId]: variables.response })); if (data.isComplete) { setCompletedResult(data); setSessionId(null); setResponses({}); } utils.earlyCareer.getDiagnostic.invalidate(); },
    onError: (error) => { setFlowError(error.message || "We could not save that response."); toast.error("We could not save that response."); },
  });

  const activeSessionId = sessionId ?? diagnostic.data?.inProgress?.id ?? null;
  const activeResponses = Object.keys(responses).length > 0 ? responses : (diagnostic.data?.inProgress?.responses as Record<string, number> | undefined) ?? {};
  const nextQuestion = useMemo(() => diagnostic.data?.questions.find((question) => !activeResponses[question.id]) ?? null, [diagnostic.data?.questions, activeResponses]);
  const result = completedResult ?? diagnostic.data?.latestResult;

  if (authLoading || diagnostic.isLoading) return <div className="mx-auto max-w-5xl px-4 py-20 text-sm md:px-8" style={{ color: "#56616D" }}>Preparing your private development reflection…</div>;
  if (!isAuthenticated) return <div className="mx-auto max-w-2xl px-4 py-20 text-center md:px-8"><p className="text-xs font-semibold uppercase tracking-widest" style={{ color: "#A47618" }}>Early Career Diagnostic</p><h1 className="mt-3 text-3xl font-semibold" style={{ color: "#0A1A2F" }}>Sign in to begin your private development reflection.</h1><Link href="/login" className="mt-6 inline-flex rounded-lg px-4 py-2.5 text-sm font-semibold" style={{ background: "#0A1A2F", color: "#F8F5F0" }}>Sign in to continue</Link></div>;
  if (diagnostic.isError) return <div className="mx-auto max-w-2xl px-4 py-20 text-center md:px-8"><p style={{ color: "#56616D" }}>We could not load the diagnostic.</p><Button className="mt-4" onClick={() => diagnostic.refetch()}>Try again</Button></div>;

  const guidance = result?.developmentGuidance;
  if (result && (!activeSessionId || completedResult)) {
    return <div className="mx-auto max-w-5xl px-4 py-10 md:px-8"><div className="rounded-3xl border bg-white p-7 md:p-10" style={{ borderColor: "#E1D9CE" }}><div className="flex items-start gap-3"><CheckCircle2 className="mt-1" style={{ color: "#A47618" }} /><div><p className="text-xs font-semibold uppercase tracking-widest" style={{ color: "#A47618" }}>Private development result</p><h1 className="mt-2 text-3xl font-semibold" style={{ color: "#0A1A2F" }}>{result.developmentalBand}</h1><p className="mt-3 max-w-2xl text-sm leading-6" style={{ color: "#56616D" }}>This reflection identifies a useful development focus. It is not a performance rating and is not shared with your manager or HR.</p></div></div><div className="mt-7 grid gap-5 md:grid-cols-[.7fr_1.3fr]"><div className="rounded-2xl p-5" style={{ background: "#F3EBD9" }}><p className="text-xs font-semibold uppercase tracking-widest" style={{ color: "#A47618" }}>Your reflection score</p><p className="mt-2 text-5xl font-semibold" style={{ color: "#0A1A2F" }}>{Math.round(result.overallScore)}</p><p className="mt-2 text-sm" style={{ color: "#56616D" }}>A private starting point for practice—not a label.</p></div>{guidance && <div className="rounded-2xl border p-5" style={{ borderColor: "#E1D9CE" }}><p className="text-xs font-semibold uppercase tracking-widest" style={{ color: "#A47618" }}>Recommended next move</p><h2 className="mt-2 text-xl font-semibold" style={{ color: "#0A1A2F" }}>{guidance.title}</h2><p className="mt-2 text-sm font-medium" style={{ color: "#0A1A2F" }}>{guidance.capabilityName}</p><p className="mt-2 text-sm leading-6" style={{ color: "#56616D" }}>{guidance.rationale}</p><div className="mt-4 rounded-xl px-4 py-3 text-sm leading-6" style={{ background: "#F8F5F0", color: "#0A1A2F" }}>{guidance.action}</div><p className="mt-3 text-sm italic" style={{ color: "#56616D" }}>{guidance.reflectionPrompt}</p></div>}</div><Button className="mt-7" variant="outline" onClick={() => { setSessionId(null); setResponses({}); start.mutate({ consent: true }); }}><RotateCcw size={15} className="mr-2" />Reflect again</Button></div></div>;
  }

  if (!activeSessionId) return <div className="mx-auto max-w-3xl px-4 py-10 md:px-8"><div className="rounded-3xl border bg-white p-7 md:p-10" style={{ borderColor: "#E1D9CE" }}><ClipboardCheck size={28} style={{ color: "#A47618" }} /><p className="mt-5 text-xs font-semibold uppercase tracking-widest" style={{ color: "#A47618" }}>Eight capabilities · 24 prompts</p><h1 className="mt-2 text-3xl font-semibold" style={{ color: "#0A1A2F" }}>Where are you building your workplace confidence?</h1><p className="mt-4 text-sm leading-7" style={{ color: "#56616D" }}>{diagnostic.data?.disclaimer}</p><div className="mt-6 flex items-start gap-3 rounded-xl p-4" style={{ background: "#F3EBD9" }}><LockKeyhole size={18} className="mt-0.5 shrink-0" style={{ color: "#0A1A2F" }} /><p className="text-sm leading-6" style={{ color: "#0A1A2F" }}>Answer based on your current experience. You will receive one practical next action; no answer is shared individually with your manager or HR.</p></div>{flowError && <div role="alert" className="mt-4 rounded-xl border px-4 py-3 text-sm" style={{ borderColor: "#C94C4C", color: "#8A2424" }}>{flowError}</div>}<Button className="mt-7" disabled={start.isPending} onClick={() => start.mutate({ consent: true })} style={{ background: "#0A1A2F", color: "#F8F5F0" }}>{start.isPending ? "Starting…" : flowError ? "Try again" : "Begin private reflection"}</Button></div></div>;

  if (!nextQuestion) return <div className="mx-auto max-w-3xl px-4 py-20 text-center md:px-8"><Sparkles className="mx-auto" style={{ color: "#A47618" }} /><h1 className="mt-4 text-2xl font-semibold" style={{ color: "#0A1A2F" }}>Your result is being prepared.</h1><p className="mt-2 text-sm" style={{ color: "#56616D" }}>Refresh in a moment to see your private development focus.</p></div>;
  const index = diagnostic.data?.questions.findIndex((question) => question.id === nextQuestion.id) ?? 0;
  return <div className="mx-auto max-w-3xl px-4 py-10 md:px-8"><div className="mb-5 flex items-center justify-between text-xs font-semibold" style={{ color: "#6B6258" }}><span>Question {index + 1} of {diagnostic.data?.questions.length}</span><span>{Math.round(((index + 1) / (diagnostic.data?.questions.length ?? 1)) * 100)}%</span></div><div className="h-1.5 rounded-full" style={{ background: "#E8E0D4" }}><div className="h-full rounded-full" style={{ width: `${((index + 1) / (diagnostic.data?.questions.length ?? 1)) * 100}%`, background: "#D4AF37" }} /></div><div className="mt-8 rounded-3xl border bg-white p-7 md:p-10" style={{ borderColor: "#E1D9CE" }}><p className="text-xs font-semibold uppercase tracking-widest" style={{ color: "#A47618" }}>{diagnostic.data?.capabilities.find((item) => item.id === nextQuestion.capabilityId)?.name}</p><h1 className="mt-3 text-2xl font-semibold leading-9" style={{ color: "#0A1A2F" }}>{nextQuestion.prompt}</h1>{flowError && <div role="alert" className="mt-5 rounded-xl border px-4 py-3 text-sm" style={{ borderColor: "#C94C4C", color: "#8A2424" }}>{flowError}{retryResponse && <button className="ml-3 font-semibold underline" onClick={() => submit.mutate(retryResponse)}>Try again</button>}</div>}<div className="mt-8 grid gap-3">{diagnostic.data?.responseScale.map((option) => <button key={option.value} disabled={submit.isPending} onClick={() => { if (!activeSessionId) return; const attempt = { sessionId: activeSessionId, questionId: nextQuestion.id, response: option.value }; setRetryResponse(attempt); submit.mutate(attempt); }} className="rounded-xl border px-4 py-3 text-left text-sm font-medium transition-colors hover:bg-[#F8F5F0] disabled:opacity-60" style={{ borderColor: "#E1D9CE", color: "#0A1A2F" }}><span className="mr-3 inline-grid h-6 w-6 place-items-center rounded-full text-xs" style={{ background: "#F3EBD9", color: "#0A1A2F" }}>{option.value}</span>{option.label}</button>)}</div><p className="mt-6 text-xs leading-5" style={{ color: "#6B6258" }}>{diagnostic.data?.disclaimer}</p></div></div>;
}
