import React, { useMemo, useState } from "react";
import { BarChart3, BellRing, FolderPlus, LockKeyhole, Trash2, UsersRound } from "lucide-react";
import { toast } from "sonner";
import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";

export default function EarlyCareerHR() {
  const { isAuthenticated } = useAuth();
  const utils = trpc.useUtils();
  const cohort = trpc.earlyCareer.getHRCohortIntelligence.useQuery(undefined, { enabled: isAuthenticated });
  const configs = trpc.earlyCareer.getNudgeConfig.useQuery(undefined, { enabled: isAuthenticated });
  const management = trpc.earlyCareer.getCohortManagement.useQuery(undefined, { enabled: isAuthenticated });
  const [audience, setAudience] = useState<"employees" | "managers">("employees");
  const [enabled, setEnabled] = useState(true);
  const [cadence, setCadence] = useState<"weekly" | "fortnightly" | "monthly">("weekly");
  const [stage, setStage] = useState<any>("all");
  const [day, setDay] = useState(1);
  const [hour, setHour] = useState(8);
  const [cohortName, setCohortName] = useState("");
  const [cohortDescription, setCohortDescription] = useState("");
  const [cohortTenantId, setCohortTenantId] = useState("");
  const [cohortManagerId, setCohortManagerId] = useState("");
  const [memberChoices, setMemberChoices] = useState<Record<number, string>>({});
  const saveNudge = trpc.earlyCareer.saveNudgeConfig.useMutation({ onSuccess: () => configs.refetch(), onError: (error) => toast.error(error.message || "Could not save nudge settings.") });
  const createCohort = trpc.earlyCareer.createCohort.useMutation({ onSuccess: () => { setCohortName(""); setCohortDescription(""); utils.earlyCareer.getCohortManagement.invalidate(); toast.success("Cohort created."); }, onError: (error) => toast.error(error.message || "Could not create cohort.") });
  const assignMember = trpc.earlyCareer.assignCohortMember.useMutation({ onSuccess: () => { utils.earlyCareer.getCohortManagement.invalidate(); utils.earlyCareer.getManagerCompanion.invalidate(); toast.success("Cohort membership updated."); }, onError: (error) => toast.error(error.message || "Could not update cohort membership.") });
  const deleteCohort = trpc.earlyCareer.deleteCohort.useMutation({ onSuccess: () => { utils.earlyCareer.getCohortManagement.invalidate(); toast.success("Cohort removed. Members remain in Early Career and can be reassigned."); }, onError: (error) => toast.error(error.message || "Could not remove cohort.") });

  const data = management.data;
  const tenantId = Number(cohortTenantId || data?.tenantIds?.[0] || 0);
  const managerOptions = useMemo(() => (data?.managers ?? []).filter((manager) => manager.tenantId === tenantId), [data?.managers, tenantId]);
  const managerName = (id: number) => data?.managers.find((manager) => manager.user.id === id)?.user.name || data?.managers.find((manager) => manager.user.id === id)?.user.email || "Assigned manager";
  const cohortMembers = (cohortId: number) => (data?.employees ?? []).filter((item) => item.profile.cohortId === cohortId);

  if (!isAuthenticated) return <div className="mx-auto max-w-4xl px-4 py-20 text-center text-[#56616D]">Sign in as an organisation owner to view cohort intelligence.</div>;
  if (management.isLoading) return <div className="mx-auto max-w-6xl px-4 py-20 text-center text-[#56616D]">Preparing cohort administration…</div>;
  if (management.isError) return <CohortQueryState title="Cohort administration could not load." message="No cohort or employee data was changed. Restore your connection and try again." onRetry={() => management.refetch()} />;
  if (!data?.canManageCohorts) return <div className="mx-auto max-w-3xl px-4 py-20 text-center"><LockKeyhole className="mx-auto h-7 w-7 text-[#A47618]" /><h1 className="mt-4 text-2xl font-semibold text-[#0A1A2F]">Organisation owner access is required.</h1><p className="mt-3 text-sm leading-6 text-[#56616D]">Cohort administration is available to organisation owners and platform administrators. Managers can use Manager Companion after employees are assigned to them.</p></div>;
  if (cohort.isLoading || configs.isLoading) return <div className="mx-auto max-w-6xl px-4 py-20 text-center text-[#56616D]">Loading organisation intelligence and nudge settings…</div>;
  if (cohort.isError || configs.isError) return <CohortQueryState title="Organisation intelligence could not load." message="Cohort membership and nudge settings remain unchanged. Please try again." onRetry={() => { cohort.refetch(); configs.refetch(); }} />;

  const submitCohort = () => {
    if (!cohortName.trim() || !tenantId || !Number(cohortManagerId)) return toast.error("Add a cohort name and select its manager.");
    createCohort.mutate({ tenantId, name: cohortName.trim(), description: cohortDescription.trim() || undefined, managerUserId: Number(cohortManagerId) });
  };

  return <div className="mx-auto max-w-6xl px-4 py-8 md:px-8"><p className="text-xs font-semibold uppercase tracking-widest text-[#A47618]">Organisation intelligence</p><h1 className="mt-2 text-3xl font-semibold text-[#0A1A2F]">Organise cohorts. Support managers.</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-[#56616D]">Create Early Career cohorts, attach each cohort to its manager, and place employees in the right support group. Private Guide conversations, practice transcripts, diagnostic answers, and labels remain excluded.</p>
    <section className="mt-7 grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><div className="rounded-2xl border bg-white p-6" style={{ borderColor: "#E1D9CE" }}><div className="flex items-center gap-3"><BarChart3 className="text-[#A47618]" /><h2 className="text-xl font-semibold text-[#0A1A2F]">Cohort snapshot</h2></div>{cohort.data?.eligible ? <><p className="mt-5 text-4xl font-semibold text-[#0A1A2F]">{cohort.data.averageOverallScore}</p><p className="text-sm text-[#56616D]">{cohort.data.cohortSize} completed reflections</p><div className="mt-6 space-y-3">{Object.entries(cohort.data.capabilityAverages ?? {}).map(([key, value]) => <div key={key}><div className="flex justify-between text-sm text-[#0A1A2F]"><span>{key.replaceAll("_", " ")}</span><span>{String(value)}</span></div><div className="mt-1 h-2 rounded-full bg-[#EEE8DF]"><div className="h-full rounded-full bg-[#D4AF37]" style={{ width: `${Number(value)}%` }} /></div></div>)}</div></> : <div className="mt-6 rounded-xl bg-[#F3EBD9] p-4 text-sm text-[#0A1A2F]">Metrics unlock after {cohort.data?.minimumCohortSize ?? 5} employees complete the diagnostic. Current cohort: {cohort.data?.cohortSize ?? 0}.</div>}<p className="mt-5 text-xs text-[#6B6258]">{cohort.data?.privacyBoundary}</p></div>
      <div className="rounded-2xl border bg-white p-6" style={{ borderColor: "#E1D9CE" }}><div className="flex items-center gap-3"><BellRing className="text-[#A47618]" /><h2 className="text-xl font-semibold text-[#0A1A2F]">Nudge controls</h2></div><div className="mt-5 flex gap-2"><Button variant={audience === "employees" ? "default" : "outline"} onClick={() => setAudience("employees")}>Employees</Button><Button variant={audience === "managers" ? "default" : "outline"} onClick={() => setAudience("managers")}>Managers</Button></div><div className="mt-4 grid grid-cols-2 gap-3 text-sm text-[#0A1A2F]"><label>Cadence<select className="mt-1 w-full rounded border p-2" value={cadence} onChange={(e) => setCadence(e.target.value as typeof cadence)}><option value="weekly">Weekly</option><option value="fortnightly">Fortnightly</option><option value="monthly">Monthly</option></select></label><label>Stage<select className="mt-1 w-full rounded border p-2" value={stage} onChange={(e) => setStage(e.target.value)}>{["all", "orient", "deliver", "connect", "navigate", "grow", "contribute", "accelerate"].map((value) => <option key={value} value={value}>{value}</option>)}</select></label><label>Day (0–6)<input className="mt-1 w-full rounded border p-2" type="number" min="0" max="6" value={day} onChange={(e) => setDay(Number(e.target.value))} /></label><label>UTC hour<input className="mt-1 w-full rounded border p-2" type="number" min="0" max="23" value={hour} onChange={(e) => setHour(Number(e.target.value))} /></label></div><label className="mt-4 flex gap-2 text-sm text-[#0A1A2F]"><input type="checkbox" checked={enabled} onChange={(e) => setEnabled(e.target.checked)} /> Enable this nudge stream</label><Button className="mt-5 w-full bg-[#0A1A2F] text-white" disabled={saveNudge.isPending} onClick={() => saveNudge.mutate({ audience, enabled, cadence, journeyStage: stage, dayOfWeek: day, hourUtc: hour })}>{saveNudge.isPending ? "Saving…" : "Save nudge controls"}</Button><p className="mt-3 text-xs text-[#6B6258]">{configs.data?.length ?? 0} configuration(s) saved.</p></div></section>
    <section className="mt-7 rounded-3xl border bg-white p-6 md:p-7" style={{ borderColor: "#E1D9CE" }}><div className="flex items-center gap-3"><FolderPlus className="text-[#A47618]" /><div><p className="text-xs font-semibold uppercase tracking-widest text-[#A47618]">Cohort administration</p><h2 className="mt-1 text-xl font-semibold text-[#0A1A2F]">Create a cohort that reports to one manager.</h2></div></div><div className="mt-5 grid gap-4 md:grid-cols-2"><label className="text-sm font-medium text-[#0A1A2F]">Cohort name<input value={cohortName} onChange={(e) => setCohortName(e.target.value)} maxLength={160} placeholder="Graduate engineering cohort" className="mt-2 w-full rounded-lg border px-3 py-2.5" style={{ borderColor: "#D9D2C5" }} /></label><label className="text-sm font-medium text-[#0A1A2F]">Manager<select value={cohortManagerId} onChange={(e) => setCohortManagerId(e.target.value)} className="mt-2 w-full rounded-lg border bg-white px-3 py-2.5" style={{ borderColor: "#D9D2C5" }}><option value="">Select a manager</option>{managerOptions.map((manager) => <option key={manager.user.id} value={manager.user.id}>{manager.user.name || manager.user.email || `User ${manager.user.id}`}</option>)}</select></label>{(data.tenantIds ?? []).length > 1 && <label className="text-sm font-medium text-[#0A1A2F]">Organisation<select value={cohortTenantId} onChange={(e) => { setCohortTenantId(e.target.value); setCohortManagerId(""); }} className="mt-2 w-full rounded-lg border bg-white px-3 py-2.5" style={{ borderColor: "#D9D2C5" }}>{data.tenantIds.map((id) => <option key={id} value={id}>Organisation {id}</option>)}</select></label>}<label className="text-sm font-medium text-[#0A1A2F]">Purpose <span className="font-normal text-[#56616D]">Optional</span><input value={cohortDescription} onChange={(e) => setCohortDescription(e.target.value)} maxLength={1000} placeholder="For example: cohort beginning a shared onboarding programme" className="mt-2 w-full rounded-lg border px-3 py-2.5" style={{ borderColor: "#D9D2C5" }} /></label></div><Button className="mt-5 bg-[#0A1A2F] text-white" disabled={createCohort.isPending} onClick={submitCohort}>{createCohort.isPending ? "Creating…" : "Create cohort"}</Button></section>
    <section className="mt-7 grid gap-6 lg:grid-cols-[.9fr_1.1fr]"><div className="rounded-3xl border bg-white p-6" style={{ borderColor: "#E1D9CE" }}><p className="text-xs font-semibold uppercase tracking-widest text-[#A47618]">Your cohorts</p><div className="mt-4 space-y-3">{data.cohorts.length ? data.cohorts.map((item) => <article key={item.id} className="rounded-2xl border p-4" style={{ borderColor: "#EDE7DF" }}><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold text-[#0A1A2F]">{item.name}</h3><p className="mt-1 text-xs text-[#56616D]">Manager: {managerName(item.managerUserId)} · {cohortMembers(item.id).length} members</p>{item.description && <p className="mt-2 text-sm text-[#56616D]">{item.description}</p>}</div><button aria-label={`Delete ${item.name}`} onClick={() => window.confirm(`Remove ${item.name}? Members will remain available for reassignment.`) && deleteCohort.mutate({ id: item.id })} className="rounded-lg border p-2 text-[#56616D] hover:text-red-700" style={{ borderColor: "#E1D9CE" }}><Trash2 className="h-4 w-4" /></button></div></article>) : <p className="rounded-xl bg-[#F8F5F0] p-4 text-sm text-[#56616D]">No cohorts yet. Create one above, then organise its members.</p>}</div></div>
      <div className="rounded-3xl border bg-white p-6" style={{ borderColor: "#E1D9CE" }}><div className="flex items-center gap-3"><UsersRound className="text-[#A47618]" /><div><p className="text-xs font-semibold uppercase tracking-widest text-[#A47618]">Member organisation</p><h2 className="mt-1 text-xl font-semibold text-[#0A1A2F]">Place employees in the right cohort.</h2></div></div><p className="mt-2 text-sm text-[#56616D]">Assigning a cohort aligns the employee to that cohort’s manager. Removing them from a cohort leaves the existing manager assignment unchanged.</p><div className="mt-5 divide-y" style={{ borderColor: "#EEE8DF" }}>{data.employees.map((item) => { const selected = memberChoices[item.employee.id] ?? String(item.profile.cohortId ?? ""); const options = data.cohorts.filter((cohort) => cohort.tenantId === item.profile.tenantId); return <div key={item.employee.id} className="grid gap-3 py-4 md:grid-cols-[1fr_minmax(190px,.8fr)_auto] md:items-center"><div><p className="font-medium text-[#0A1A2F]">{item.employee.name || item.employee.email || "Employee"}</p><p className="mt-1 text-xs text-[#6B6258]">{item.profile.roleTitle || "Early-career employee"} · {item.profile.managerUserId ? `Manager: ${managerName(item.profile.managerUserId)}` : "No manager assigned"}</p></div><select value={selected} onChange={(e) => setMemberChoices({ ...memberChoices, [item.employee.id]: e.target.value })} className="rounded-lg border bg-white px-3 py-2 text-sm" style={{ borderColor: "#D9D2C5" }}><option value="">No cohort</option>{options.map((cohort) => <option key={cohort.id} value={cohort.id}>{cohort.name} — {managerName(cohort.managerUserId)}</option>)}</select><Button size="sm" disabled={assignMember.isPending || selected === String(item.profile.cohortId ?? "")} onClick={() => assignMember.mutate({ employeeUserId: item.employee.id, cohortId: selected ? Number(selected) : null })}>Save</Button></div>; })}</div></div></section>
    <p className="mt-6 flex items-center gap-2 text-xs text-[#6B6258]"><LockKeyhole size={14} /> Owner-only cohort controls. Private developmental content remains excluded.</p>
  </div>;
}

function CohortQueryState({ title, message, onRetry }: { title: string; message: string; onRetry: () => void }) {
  return <div className="mx-auto max-w-2xl px-4 py-20 text-center"><LockKeyhole className="mx-auto h-7 w-7 text-[#A47618]" /><h1 className="mt-4 text-2xl font-semibold text-[#0A1A2F]">{title}</h1><p className="mt-3 text-sm leading-6 text-[#56616D]">{message}</p><Button className="mt-6 bg-[#0A1A2F] text-white" onClick={onRetry}>Try again</Button></div>;
}
