import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Download, Loader2, LockKeyhole, ShieldCheck, UsersRound } from "lucide-react";
import React from "react";

type Dimension = { id: string; label: string };
type Snapshot = Record<string, any>;

function ScoreTile({ label, value, note }: { label: string; value: number | null | undefined; note: string }) {
  return <Card className="border-slate-200 shadow-none"><CardContent className="p-4"><p className="text-[11px] font-semibold uppercase tracking-widest text-[#12345A]">{label}</p><p className="mt-2 text-2xl font-bold text-[#0A1A2F]">{typeof value === "number" ? `${value}/100` : "—"}</p><p className="mt-2 text-xs leading-5 text-slate-500">{note}</p></CardContent></Card>;
}

export function IndividualReportPreview({ open, onOpenChange, campaignName, completedAt, score, dimensions, onDownload, exporting }: { open: boolean; onOpenChange: (open: boolean) => void; campaignName: string; completedAt: Date | string; score: Snapshot; dimensions: Dimension[]; onDownload: () => void; exporting: boolean }) {
  const priorities = new Set<string>(score.priorities ?? []);
  const strengths = new Set<string>(score.strengths ?? []);
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[90vh] max-w-3xl overflow-y-auto border-[#12345A]/20 bg-[var(--color-ln-ivory)] p-0"><div className="border-b border-[#12345A]/15 bg-[#0A1A2F] px-6 py-6 text-white"><img src="/logo.png" alt="LevelNext" className="h-8 w-auto brightness-0 invert" /><Badge className="mt-5 bg-[#F2B705] text-[#12345A] hover:bg-[#F2B705]">Private development report preview</Badge><DialogHeader className="mt-3"><DialogTitle className="text-2xl text-white">Critical Thinking in Decision Making</DialogTitle><DialogDescription className="text-slate-200">{campaignName} · completed {new Date(completedAt).toLocaleDateString(undefined, { year: "numeric", month: "long", day: "numeric" })}</DialogDescription></DialogHeader></div><div className="space-y-6 px-6 py-6"><div className="grid gap-3 sm:grid-cols-3"><ScoreTile label="Applied judgment" value={score.appliedJudgmentScore} note="Scenario choices in the current response set." /><ScoreTile label="Confidence" value={score.meanConfidence} note={score.calibration?.label ?? "Current confidence pattern."} /><ScoreTile label="Environment" value={score.environmentScore} note={score.environmentBand ?? "Reported separately."} /></div><div><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-[#12345A]" /><h3 className="font-semibold text-[#0A1A2F]">Capability profile</h3></div><div className="mt-3 grid gap-2 sm:grid-cols-2">{dimensions.map((dimension) => { const value = score.dimensionScores?.[dimension.id]; const tag = strengths.has(dimension.id) ? "Relative strength" : priorities.has(dimension.id) ? "Development priority" : "Current signal"; return <div key={dimension.id} className="flex items-center justify-between rounded-lg border border-slate-200 bg-white px-3 py-2.5"><div><p className="text-sm font-medium">{dimension.label}</p><p className="text-xs text-slate-500">{tag}</p></div><p className="font-bold text-[#12345A]">{typeof value === "number" ? `${value}/100` : "—"}</p></div>; })}</div></div><div className="rounded-xl border border-[#F2B705]/40 bg-[#F2B705]/10 p-4 text-sm leading-6 text-slate-700"><div className="flex gap-2"><LockKeyhole className="mt-1 h-4 w-4 shrink-0 text-[#12345A]" /><p>This downloadable report is private to you. It supports development planning; it is not a performance rating, intelligence test, or employment decision tool.</p></div></div></div><DialogFooter className="border-t border-[#12345A]/10 bg-white px-6 py-4 sm:justify-between"><p className="hidden max-w-md text-xs text-slate-500 sm:block">The PDF includes your development summary, capability profile, and 30-day practice plan.</p><Button onClick={onDownload} disabled={exporting} className="bg-[#12345A]"><>{exporting ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Download className="mr-2 h-4 w-4" />}{exporting ? "Preparing PDF" : "Download development report"}</></Button></DialogFooter></DialogContent></Dialog>;
}

export function TeamReportPreview({ open, onOpenChange, campaignName, reportingGroup, participantCount, minTeamSize, aggregate, dimensions, onDownload, exporting }: { open: boolean; onOpenChange: (open: boolean) => void; campaignName: string; reportingGroup: string; participantCount: number; minTeamSize: number; aggregate: Snapshot; dimensions: Dimension[]; onDownload: () => void; exporting: boolean }) {
  const priorities = new Set<string>(aggregate.sharedPriorities ?? []); const strengths = new Set<string>(aggregate.sharedStrengths ?? []);
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[90vh] max-w-3xl overflow-y-auto border-[#12345A]/20 bg-[var(--color-ln-ivory)] p-0"><div className="border-b border-[#12345A]/15 bg-[#0A1A2F] px-6 py-6 text-white"><img src="/logo.png" alt="LevelNext" className="h-8 w-auto brightness-0 invert" /><Badge className="mt-5 bg-[#F2B705] text-[#12345A] hover:bg-[#F2B705]">Anonymised team report preview</Badge><DialogHeader className="mt-3"><DialogTitle className="text-2xl text-white">Critical Thinking team development</DialogTitle><DialogDescription className="text-slate-200">{campaignName} · {reportingGroup} · {participantCount} completed participants</DialogDescription></DialogHeader></div><div className="space-y-6 px-6 py-6"><div className="grid gap-3 sm:grid-cols-3"><ScoreTile label="Applied judgment" value={aggregate.averageAppliedJudgmentScore} note="Group-level average only." /><ScoreTile label="Behavioural practice" value={aggregate.averageBehaviouralScore} note="Group-level average only." /><ScoreTile label="Environment" value={aggregate.averageEnvironmentScore} note="Reported separately from capability." /></div><div><div className="flex items-center gap-2"><UsersRound className="h-5 w-5 text-[#12345A]" /><h3 className="font-semibold text-[#0A1A2F]">Shared capability profile</h3></div><div className="mt-3 grid gap-2 sm:grid-cols-2">{dimensions.map((dimension) => { const value = aggregate.dimensionAverages?.[dimension.id]; const tag = strengths.has(dimension.id) ? "Shared strength" : priorities.has(dimension.id) ? "Shared priority" : "Group signal"; return <div key={dimension.id} className="flex items-center justify-between rounded-lg border border-slate-200 bg-white px-3 py-2.5"><div><p className="text-sm font-medium">{dimension.label}</p><p className="text-xs text-slate-500">{tag}</p></div><p className="font-bold text-[#12345A]">{typeof value === "number" ? `${value}/100` : "—"}</p></div>; })}</div></div><div className="rounded-xl border border-[#F2B705]/40 bg-[#F2B705]/10 p-4 text-sm leading-6 text-slate-700"><div className="flex gap-2"><LockKeyhole className="mt-1 h-4 w-4 shrink-0 text-[#12345A]" /><p>This report is available because the completed group meets the configured anonymity threshold of {minTeamSize}. It contains no named individual scores and must not be used to rank people.</p></div></div></div><DialogFooter className="border-t border-[#12345A]/10 bg-white px-6 py-4 sm:justify-between"><p className="hidden max-w-md text-xs text-slate-500 sm:block">The PDF includes group patterns, team routines, and a discussion guide.</p><Button onClick={onDownload} disabled={exporting} className="bg-[#12345A]"><>{exporting ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Download className="mr-2 h-4 w-4" />}{exporting ? "Preparing PDF" : "Download team report"}</></Button></DialogFooter></DialogContent></Dialog>;
}
