import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Mail, Send, ShieldCheck } from "lucide-react";
import React, { useState } from "react";

export function CriticalThinkingShareDialog({ open, onOpenChange, onShare, sharing }: { open: boolean; onOpenChange: (open: boolean) => void; onShare: (managerEmail: string) => Promise<void>; sharing: boolean }) {
  const [managerEmail, setManagerEmail] = useState(""); const [confirmed, setConfirmed] = useState(false); const [error, setError] = useState<string | null>(null);
  const submit = async () => { const email = managerEmail.trim().toLowerCase(); if (!/^\S+@\S+\.\S+$/.test(email)) { setError("Enter your manager’s work email address."); return; } if (!confirmed) { setError("Confirm that you have chosen to share this private report."); return; } setError(null); await onShare(email); };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-lg"><DialogHeader><div className="mb-2 flex h-10 w-10 items-center justify-center rounded-full bg-[#12345A]/10"><Mail className="h-5 w-5 text-[#12345A]" /></div><DialogTitle>Share your report with a manager</DialogTitle><DialogDescription>Your individual development report remains private until you choose to share it. Team reports and your raw reflection responses are never included.</DialogDescription></DialogHeader><div className="space-y-5 py-3"><div className="space-y-2"><Label htmlFor="ctdm-manager-email">Manager’s work email</Label><Input id="ctdm-manager-email" type="email" value={managerEmail} onChange={(event) => setManagerEmail(event.target.value)} placeholder="manager@company.com" autoComplete="email" /></div><div className="rounded-lg border border-[#F2B705]/40 bg-[#fff8db] p-3 text-sm leading-6 text-slate-700"><ShieldCheck className="mr-2 inline h-4 w-4 text-[#12345A]" />We prepare the same private PDF shown in your preview. Your device’s share sheet opens where supported; otherwise, an email draft opens and the PDF downloads for you to attach.</div><div className="flex items-start gap-3"><Checkbox id="ctdm-share-confirmation" checked={confirmed} onCheckedChange={(next) => setConfirmed(next === true)} /><Label htmlFor="ctdm-share-confirmation" className="cursor-pointer text-sm leading-5">I choose to share my private developmental report with this manager for a development conversation.</Label></div>{error && <p className="text-sm text-red-700">{error}</p>}</div><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)} disabled={sharing}>Cancel</Button><Button className="bg-[#12345A]" onClick={submit} disabled={sharing}><Send className="mr-2 h-4 w-4" />{sharing ? "Preparing secure share…" : "Prepare manager share"}</Button></DialogFooter></DialogContent></Dialog>;
}
