import { useRef, useState } from "react";
import { Check, FileUp, ShieldCheck, UserRound } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";

type Props = { pilotId: number };
const requirementStatuses = ["not_started", "in_review", "approved", "blocked", "not_applicable"] as const;
const documentStatuses = ["uploaded", "in_review", "approved", "needs_action", "archived"] as const;

function titleCase(value: string) { return value.replace(/_/g, " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function readFileBase64(file: File) { return new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = reject; reader.readAsDataURL(file); }); }

export function ProofSecurityWorkspace({ pilotId }: Props) {
  const workspace = trpc.behaviourChangeProof.securityWorkspace.useQuery({ pilotId });
  const upload = trpc.behaviourChangeProof.uploadSecurityDocument.useMutation({ onSuccess: () => void workspace.refetch() });
  const updateDocument = trpc.behaviourChangeProof.updateSecurityDocument.useMutation({ onSuccess: () => void workspace.refetch() });
  const updateRequirement = trpc.behaviourChangeProof.updateSecurityRequirement.useMutation({ onSuccess: () => void workspace.refetch() });
  const createRequirement = trpc.behaviourChangeProof.createSecurityRequirement.useMutation({ onSuccess: () => { void workspace.refetch(); setRequirementKey(""); setRequirementTitle(""); setRequirementDescription(""); } });
  const inputRef = useRef<HTMLInputElement>(null);
  const [file, setFile] = useState<File | null>(null); const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [message, setMessage] = useState("");
  const [requirementKey, setRequirementKey] = useState(""); const [requirementTitle, setRequirementTitle] = useState(""); const [requirementDescription, setRequirementDescription] = useState("");
  const onUpload = async () => {
    if (!file || !title.trim()) return;
    try { const fileBase64 = await readFileBase64(file); upload.mutate({ pilotId, title: title.trim(), description: description.trim() || undefined, fileName: file.name, contentType: file.type || "application/octet-stream", fileBase64 }); setMessage("Document uploaded. Assign a review owner and status below."); setFile(null); setTitle(""); setDescription(""); if (inputRef.current) inputRef.current.value = ""; } catch { setMessage("The file could not be read. Choose a file no larger than 5 MB."); }
  };
  if (workspace.isLoading) return <div className="rounded-xl border border-[#DCE3EA] bg-white p-6 text-sm text-slate-500">Preparing security workspace…</div>;
  if (!workspace.data) return <div className="rounded-xl border border-red-200 bg-red-50 p-5 text-sm text-red-700">Security workspace unavailable.</div>;
  const { documents, requirements } = workspace.data;
  return <div className="space-y-6">
    <div className="rounded-xl bg-[#EEF4F9] p-5 text-sm leading-6 text-slate-700"><div className="flex gap-3"><ShieldCheck className="mt-0.5 shrink-0 text-[#0A1A2F]" size={20} /><div><b>Track the actual review work.</b><p className="mt-1">This workspace records documents, owners, requirements, and approvals. It is not itself a certification, DPA, security assessment, or approval decision.</p></div></div></div>
    <Card className="border-[#DCE3EA] bg-white"><CardHeader><CardTitle className="flex items-center gap-2 text-lg text-[#0A1A2F]"><FileUp size={18} /> Evidence documents</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 md:grid-cols-[1fr_1fr] "><Input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Document title" className="border-[#C9D4DF]" /><input ref={inputRef} type="file" onChange={(event) => setFile(event.target.files?.[0] ?? null)} className="block w-full text-sm" /></div><Textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="What does this document answer or evidence?" className="min-h-20 border-[#C9D4DF]" /><Button disabled={!file || !title.trim() || upload.isPending} onClick={() => void onUpload()} className="bg-[#D4AF37] text-[#0A1A2F]">{upload.isPending ? "Uploading…" : "Upload security document"}</Button>{message && <p className="text-sm text-emerald-700">{message}</p>}{upload.error && <p className="text-sm text-red-600">{upload.error.message}</p>}
      <div className="space-y-3 border-t border-[#EEF1F4] pt-4">{documents.length ? documents.map((document) => <div key={document.id} className="rounded-lg border border-[#EEF1F4] p-4"><div className="flex flex-col gap-3 md:flex-row md:items-start md:justify-between"><div><p className="font-semibold text-[#0A1A2F]">{document.title}</p><p className="mt-1 text-xs text-slate-500">{document.contentType} · {(document.fileSize / 1024).toFixed(0)} KB</p>{document.description && <p className="mt-2 text-sm text-slate-600">{document.description}</p>}<a href={document.storageUrl} target="_blank" rel="noreferrer" className="mt-2 inline-block text-sm font-medium text-[#0A1A2F] underline">Open uploaded file</a></div><select value={document.status} onChange={(event) => updateDocument.mutate({ pilotId, documentId: document.id, status: event.target.value as typeof documentStatuses[number] })} className="h-9 rounded-md border border-[#C9D4DF] bg-white px-2 text-sm text-[#0A1A2F]">{documentStatuses.map((status) => <option key={status} value={status}>{titleCase(status)}</option>)}</select></div><div className="mt-3 grid gap-2 md:grid-cols-2"><Input defaultValue={document.reviewOwnerName ?? ""} placeholder="Review owner name" onBlur={(event) => updateDocument.mutate({ pilotId, documentId: document.id, reviewOwnerName: event.target.value, status: document.status })} /><Input defaultValue={document.reviewOwnerEmail ?? ""} placeholder="Review owner email" onBlur={(event) => updateDocument.mutate({ pilotId, documentId: document.id, reviewOwnerEmail: event.target.value, status: document.status })} /></div><Textarea defaultValue={document.reviewNotes ?? ""} placeholder="Review notes or outstanding question" className="mt-2 min-h-16 text-sm" onBlur={(event) => updateDocument.mutate({ pilotId, documentId: document.id, reviewNotes: event.target.value, status: document.status })} /></div>) : <p className="text-sm text-slate-500">No evidence documents uploaded yet.</p>}</div></CardContent></Card>
    <Card className="border-[#DCE3EA] bg-white"><CardHeader><CardTitle className="flex items-center gap-2 text-lg text-[#0A1A2F]"><UserRound size={18} /> Requirement-level approval tracking</CardTitle></CardHeader><CardContent className="space-y-3">{requirements.map((requirement) => <div key={requirement.id} className="rounded-lg border border-[#EEF1F4] p-4"><div className="flex flex-col gap-3 md:flex-row md:items-start md:justify-between"><div><p className="font-semibold text-[#0A1A2F]">{requirement.title}</p><p className="mt-1 text-sm leading-5 text-slate-600">{requirement.description}</p></div><select value={requirement.status} onChange={(event) => updateRequirement.mutate({ pilotId, requirementId: requirement.id, status: event.target.value as typeof requirementStatuses[number] })} className="h-9 rounded-md border border-[#C9D4DF] bg-white px-2 text-sm text-[#0A1A2F]">{requirementStatuses.map((status) => <option key={status} value={status}>{titleCase(status)}</option>)}</select></div><div className="mt-3 grid gap-2 md:grid-cols-2"><Input defaultValue={requirement.ownerName ?? ""} placeholder="Review owner name" onBlur={(event) => updateRequirement.mutate({ pilotId, requirementId: requirement.id, ownerName: event.target.value, status: requirement.status })} /><Input defaultValue={requirement.ownerEmail ?? ""} placeholder="Review owner email" onBlur={(event) => updateRequirement.mutate({ pilotId, requirementId: requirement.id, ownerEmail: event.target.value, status: requirement.status })} /></div><Textarea defaultValue={requirement.reviewNote ?? ""} placeholder="Approval note, caveat, or blocker" className="mt-2 min-h-16 text-sm" onBlur={(event) => updateRequirement.mutate({ pilotId, requirementId: requirement.id, reviewNote: event.target.value, status: requirement.status })} /></div>)}
      <details className="rounded-lg bg-[#F8F5F0] p-4"><summary className="cursor-pointer text-sm font-semibold text-[#0A1A2F]">Add a pilot-specific requirement</summary><div className="mt-4 grid gap-3"><Input value={requirementKey} onChange={(event) => setRequirementKey(event.target.value)} placeholder="Short requirement key, e.g. legal-review" /><Input value={requirementTitle} onChange={(event) => setRequirementTitle(event.target.value)} placeholder="Requirement title" /><Textarea value={requirementDescription} onChange={(event) => setRequirementDescription(event.target.value)} placeholder="What must be reviewed or approved?" className="min-h-20" /><Button disabled={!requirementKey.trim() || !requirementTitle.trim() || !requirementDescription.trim() || createRequirement.isPending} onClick={() => createRequirement.mutate({ pilotId, requirementKey, title: requirementTitle, description: requirementDescription })} variant="outline" className="w-fit border-[#0A1A2F] text-[#0A1A2F]">Add requirement <Check size={15} /></Button></div></details>
    </CardContent></Card>
  </div>;
}
